--[[

AddTextEntry('<gameName>', '<replaced name>')

When vehicles display NULL on police calls, boosting, racing, etc, usually means there's no given name for it.
Anytime you add a new vehicle, simply open the Vehicle's vehicle.meta and look for <gameName>. (Also can be spawn model)
Then you can name it to anything you like on the second part of the AddTextEntry

EX: https://i.imgur.com/X9j127E.png

]]--
-- Emergency Vehicles
AddTextEntry('e20exp', '2020 EMS Ford Explorer')
AddTextEntry('fordambo', 'Ambulance')
AddTextEntry('ec145med', 'Eurocopter EC145')
AddTextEntry('Bell 412', 'safr412')
AddTextEntry('largeboat', 'EMS Boat')
AddTextEntry('pierce1', 'Pierce Firetruck')
AddTextEntry('pcvpi', '2011 Police Ford CVPI')
AddTextEntry('p14tesla', '2014 Police Tesla Model S')
AddTextEntry('p16tau', '2016 Police Ford Taurus')
AddTextEntry('p18cha', '2018 Police Dodge Charger')
AddTextEntry('p18tah', '2018 Police Chevorlet Tahoe')
AddTextEntry('p18xl', '2018 Police Ford 1500')
AddTextEntry('p20exp', '2020 Police Ford Explorer')
AddTextEntry('p21dur', '2021 Police Dodge Durango')
AddTextEntry('p21tah', '2021 Police Chevorlet Tahoe')
AddTextEntry('SOTRUCK', 'Police Ford F-350')
AddTextEntry('p4x4', '2020 Police Polaris Ranger')
AddTextEntry('intchar', 'Police Dodge Charger Hellcat')
AddTextEntry('npolstang', 'Police Ford Mustang')
AddTextEntry('npolchal', 'Police Dodge Challenger')
AddTextEntry('npolvette', 'Police Chevorlet Corvette C7')
AddTextEntry('bearcatrb', 'Bearcat')
AddTextEntry('14suvrb', 'Police Chevorlet Suburban')
AddTextEntry('pbike', 'Police Bicycle')
AddTextEntry('policebikerb', 'Offroad Police Motorbike')
AddTextEntry('1200RT', 'Police BMW 1200RT')
AddTextEntry('pboat', 'Police Tug Boat')
AddTextEntry('predator2', 'Police Predator')
AddTextEntry('as350', 'AS350')
AddTextEntry('c3swathawk', 'Swathawk')
AddTextEntry('buzzard2', 'Buzzard')
-- Custom DF Class
AddTextEntry('na6', 'Mazda Miata')
AddTextEntry('rmod240sx', 'Nissan 240SX')
AddTextEntry('silvia3', 'Nissan 240SX (s14)')
AddTextEntry('s15yoshio', 'Nissan S15')
AddTextEntry('evoix', 'Mitsubishi EVO IX')
AddTextEntry('razerchaser', 'Toyota Chaser')
AddTextEntry('datsun910', '1982 Datsun Bluebird 910 SSS')
AddTextEntry('ae86', '1985 Toyota Sprinter Trueno GT Apex (AE86)')
AddTextEntry('rx7rb', 'Mazda RX-7')
AddTextEntry('sentineldm', 'Ubermach Sentinel Custom')
AddTextEntry('GODzC6FD', 'Chevorlet Corvette C6')
AddTextEntry('GODzC6FD_RC', 'Chevorlet Corvette C6 RC')
AddTextEntry('bugfd', 'Ford Mustang')
-- Custom X Class
AddTextEntry('supersport', '2011 Bugatti Veyron Super Sport')
AddTextEntry('agerars', '2017 Koenigsegg Agera RS')
AddTextEntry('rmodjesko', 'Koenigsegg Jesko')
AddTextEntry('bolide', 'Bugatti Bolide')
AddTextEntry('chiron', 'Bugatti Chiron')
AddTextEntry('gt1', 'Porsche GT1')
AddTextEntry('gemera', '2021 Koenigsegg Gemera')
-- Custom S Class
AddTextEntry('500gtrlam', '1999 Lamborghini Diablo GTR')
AddTextEntry('600lt', 'Mclaren 600LT')
AddTextEntry('f8t', 'Ferrari F8 Tributo')
AddTextEntry('lp700r', 'Lamborghini LP700 R')
AddTextEntry('gtr', 'Nissan GTR')
AddTextEntry('r820', 'Audi R8')
AddTextEntry('lfa', '2010 Lexus LFA')
AddTextEntry('lwhuracan', 'Lamborghini Huracan')
AddTextEntry('rmodf12tdf', 'Ferrari F12')
AddTextEntry('rmodf40', 'Ferrari F40')
AddTextEntry('rmodgtr50', 'Italdesign Nissan GTR-50')
AddTextEntry('rmodsianr', 'Lamborghini Sian')
AddTextEntry('pts21', 'Porsche 911 Turbo S')
AddTextEntry('pgt3', 'Porsche GT3')
AddTextEntry('aimgainnsx', '2016 Honda NSX')
AddTextEntry('elva', 'McLaren Elva')
AddTextEntry('evo2', 'Lamborghini Huracan Evo 2')
AddTextEntry('gallardolw', 'Lamborghini Gallardo LW')
AddTextEntry('lp670', 'Lamborghini Murcielago LP-670')
AddTextEntry('lwlp670', 'Lamborghini Murcielago LP-670 LW')
AddTextEntry('lw458s', 'Ferrari 458 LW')
AddTextEntry('cx75', 'Jaguar CX-75')
AddTextEntry('rmodessenza', 'Lamborghini Essenza')
AddTextEntry('moss', 'Mercedes SLR Stirling Moss')
AddTextEntry('shelby20', 'Ford GT500')
AddTextEntry('rr20amggt', 'Mercedes-Benz AMG GT')
AddTextEntry('chr20', 'Dodge Charger (Redeye)')
AddTextEntry('urustc', 'Lamborghini Urus')
AddTextEntry('I8', 'BMW I8')
AddTextEntry('tesroad20', '2020 Tesla Roadster')
AddTextEntry('ocnlamtmc', 'Lamborghini Terzo Millennio')
AddTextEntry('evija', 'Lotus Evija')
AddTextEntry('zeno_USA', 'Overflod Zeno')
AddTextEntry('ignus_USA', 'Pegassi Ignus')
AddTextEntry('champion_USA', 'Dewbauchee Champion')
AddTextEntry('comet7_USA', 'Pfister Comet S2 Cabrio')
AddTextEntry('eg6', 'Honda Civic (EG6)')
AddTextEntry('spoonek', 'Honda Civic (EK9)')
AddTextEntry('fnfcivic', '1993 Honda Civic (FnF)')
AddTextEntry('monroec', 'Pegassi Monroe Custom')
AddTextEntry('sennas', 'Mclaren Senna')
AddTextEntry('sennasgtr', 'Mclaren Senna GTR')
AddTextEntry('zondar', 'Pagani Zonda R')
AddTextEntry('fxxk', 'Ferrari FXXK')
AddTextEntry('clklm', 'Mercedes-Benz CLK LM')
AddTextEntry('castrolsupra', 'Toyota Supra')
AddTextEntry('skyline', 'Nissan Skyline GT-R (R34)')
AddTextEntry('r33vspec', 'Nissan Skyline GT-R V-Spec (R33)')
AddTextEntry('r32', 'Nissan Skyline GT-R (R32)')
AddTextEntry('na1', '1992 Honda NSX')
AddTextEntry('laferrari', 'Ferrari LaFerrari')
AddTextEntry('p1', 'McLaren P1')
AddTextEntry('918', 'Porsche 918')
AddTextEntry('rmodp1gtr', 'McLaren P1 GTR')
AddTextEntry('por718gt4', '2020 Porsche 718 Cayman GT4')
AddTextEntry('C7R', 'Chevrolet Corvette C7R GTLM')
AddTextEntry('pgt2', '2012 Porsche 911 GT2 RS')
AddTextEntry('911rwb', '1993 Porsche 911 (993) RWB "Rotana"')
AddTextEntry('viper', '2016 SRT Viper')
AddTextEntry('acr', '2016 SRT Viper ACR')
AddTextEntry('r8hycade', 'Audi R8 Hycade')
AddTextEntry('rmodm8gte', 'BMW M8 GTE')
-- Custom A Class
AddTextEntry('16challenger', 'Dodge Challenger')
AddTextEntry('16charger', '2016 Dodge Charger')
AddTextEntry('21camaro', '2021 Chevrolet Camaro')
AddTextEntry('67GT500', '1967 Ford Mustang GT500')
AddTextEntry('99viper', '1999 Dodge Viper')
AddTextEntry('rs6', 'Audi RS6')
AddTextEntry('m2', 'BMW M2')
AddTextEntry('bmwm3e92', 'BMW M3')
AddTextEntry('m3e92gts', 'BMW M3 GTS')
AddTextEntry('rmodm3e36', 'BMW M3 E36')
AddTextEntry('M3E46', 'BMW M3 E46')
AddTextEntry('f82', 'BMW M4')
AddTextEntry('f82hs', 'BMW M4')
AddTextEntry('f82lw', 'BMW M4')
AddTextEntry('f82st', 'BMW M4')
AddTextEntry('f824slw', 'BMW M4')
AddTextEntry('bmci', 'BMW M5')
AddTextEntry('m5e60', 'BMW M5 E60')
AddTextEntry('bmwm8', 'BMW M8')
AddTextEntry('zl12017', 'Chevrolet Camaro')
AddTextEntry('c7', 'Chevrolet C7')
AddTextEntry('mgt', 'Ford Mustang')
AddTextEntry('ctsv16', '2016 Cadillac CTS-V')
AddTextEntry('FK8', '2018 Honda Civic Type-R')
AddTextEntry('srt8', 'Jeep SRT8')
AddTextEntry('lc500', '2020 Lexus LC500')
AddTextEntry('mers63c', '2017 Mercedes-Benz S63 AMG Cabriolet')
AddTextEntry('stingray', 'Chevorlet Corvette C8')
AddTextEntry('rmodgt63', 'Mercedes GT63')
AddTextEntry('C63AMG', 'Mercedes C63 AMG')
AddTextEntry('rs62', '2020 Audi RS6 Avant')
AddTextEntry('ninjah2', 'Kawasaki H2R')
AddTextEntry('z1000', 'Kawasaki Z1000')
AddTextEntry('panigale', 'Ducati Panigale')
AddTextEntry('yamahar1', 'Yamaha R1')
AddTextEntry('BMW1100R', 'BMW 1100R Street Fighter')
AddTextEntry('BMWS1000RR', '2016 BMW S1000RR')
AddTextEntry('sti17', '2017 Subaru WRX STI')
AddTextEntry('supra2', 'Toyota Supra Mk4')
AddTextEntry('stradale18', '2016 Maserati GranTurismo')
AddTextEntry('teslapd', 'Tesla Model S Prior Design')
AddTextEntry('models', 'Tesla Model S')
AddTextEntry('teslamodels', 'Tesla Model S')
AddTextEntry('teslax', 'Tesla Model X')
AddTextEntry('rmodbacalar', 'Bentley Bacalar')
AddTextEntry('rmodmartin', 'Aston Martin DBS')
AddTextEntry('razerpandemraptor', 'Ford Raptor Pandem')
AddTextEntry('300srt8', 'Chrysler 300 SRT8')
AddTextEntry('hellephantdurango', 'Dodge Durango Hellephant')
AddTextEntry('rr70bosswide', '1977 Ford Mustang Boss')
AddTextEntry('rrrcf', 'Lexus RC-F')
AddTextEntry('taycan', 'Porsche Taycan')
AddTextEntry('rebeld', 'Karin Rebel Custom')
AddTextEntry('Mitsubishi Lancer Evolution IX Voltex', 'topfoil')
AddTextEntry('2012 Mercedes-Benz C63 AMG Coupe Black Series', 'mbc63')
AddTextEntry('1969 Dodge Charger', 'rmodcharger69')
-- Custom B Class
AddTextEntry('4runner', 'Toyota 4Runner')
AddTextEntry('19S650', '2019 Mercedes-Benz S650 Maybach')
AddTextEntry('21escalade', '2021 Cadillac Escalade')
AddTextEntry('928gts', '1993 Porsche 928 GTS')
AddTextEntry('k5', '1979 Chevrolet Hoonigan K5 Blazer')
AddTextEntry('camaro02', '2002 Chevrolet Camaro')
AddTextEntry('tahoe08', '2008 Chevrolet Tahoe')
AddTextEntry('wildtrak', '2021 Ford Bronco Wildtrak')
AddTextEntry('bbentayga', '2016 Bentley Bentayga')
AddTextEntry('benze55', 'Mercedes-Benz E55 AMG')
AddTextEntry('alpinae30', 'BMW E30')
AddTextEntry('e34', 'BMW E34')
AddTextEntry('x5m2016', '2016 BMW X5')
AddTextEntry('ocni422spe', '2020 BMW i4')
AddTextEntry('z3', 'BMW Z3')
AddTextEntry('brz13', 'Subaru BRZ')
AddTextEntry('c10custom', 'Chevrolet C-10 Stepside Custom')
AddTextEntry('camaro69', '1969 Chevrolet Camaro SS')
AddTextEntry('camaro70', '1970 Chevrolet Camaro Z28')
AddTextEntry('can', '2018 Can Am Maverick')
AddTextEntry('cont', '2020 Lincoln Continental')
AddTextEntry('corvette70', '1970 Chevrolet Corvette')
AddTextEntry('crownvic2011', 'Ford Crown Victoria')
AddTextEntry('cullinan', 'Rolls Royce Cullinan')
AddTextEntry('ep3', '2001 Honda Civic Type-R')
AddTextEntry('wdf350', 'Ford F350')
AddTextEntry('f450plat', '2021 Ford F-450 Platinum')
AddTextEntry('flightning99', '1999 Ford F-150 SVT Lightning')
AddTextEntry('ford32hulagirl', '1932 Ford HulaGirl')
AddTextEntry('fordc32h', '1932 Ford V-8 Coupé 2')
AddTextEntry('f150', 'Ford F150 Raptor')
AddTextEntry('foxraptor', 'Ford F150 Raptor')
AddTextEntry('w463a1', 'Mercedes-Benz G-Class Brabus')
AddTextEntry('golfgti', 'Volkswagon Golf GTI')
AddTextEntry('jeepg', 'Jeep Gladiator')
AddTextEntry('mansrr', '2020 Land Rover Range Rover Vogue Mansory')
AddTextEntry('mlnovitec', 'Maserati Levante Novitec')
AddTextEntry('pacificasb', '2020 Chrysler Pacifica Limited S')
AddTextEntry('passat', '2016 Volkswagen Passat')
AddTextEntry('peugeot206', 'Peugeot 206 GTi')
AddTextEntry('polar06seirra', '2006 GMC Sierra')
AddTextEntry('ramsrt10', 'Dodge Ram SRT-10')
AddTextEntry('rmodsuprapandem', 'Toyota Supra')
AddTextEntry('silv2500hd', 'Chevrolet Silverado 2500 HD')
AddTextEntry('silv20', 'Chevrolet Silverado (Single Cab)')
AddTextEntry('subisti08', 'Subaru WRX STI')
AddTextEntry('subwrx', '2004 Subaru WRX STI')
AddTextEntry('wraith', '2016 Rolls Royce Wraith')
AddTextEntry('GODzBGDCADIMAX', '2018 GMC CadimaX 3500HD')
AddTextEntry('20f450', '2020 Ford F-450')
AddTextEntry('f350d', '2020 Ford F-350')
AddTextEntry('GODz3500HDWELDER', '2020 GMC Sierra 3500HD')
AddTextEntry('golfmk6', 'Volkswagon Golf (Mk6)')
AddTextEntry('dc5', 'Acura RSX (DC5)')
AddTextEntry('a6', 'Audi A6')
AddTextEntry('voodoo_caddys', 'Voodoo Caddy S')
AddTextEntry('370z', 'Nissan 370z')
AddTextEntry('19ramdonk', '2019 Dodge Ram Donk')
AddTextEntry('denali18', 'GMC Denali')
AddTextEntry('dodgetrx', 'Dodge Ram TRX')
AddTextEntry('slammedf100', 'Ford F100 Slammed')
AddTextEntry('dababy', 'Dababy Car')
AddTextEntry('09fordRS', '2009 Ford Focus RS')
AddTextEntry('17fordRS', '2017 Ford Focus RS')
AddTextEntry('accord20', '2020 Honda Accord')
AddTextEntry('camry18', '2018 Toyota Camry')
AddTextEntry('infinitig35', 'Infiniti G35')
AddTextEntry('gmcat4', 'GMC AT4')
AddTextEntry('is300', 'Lexus IS300')
AddTextEntry('rsq8m', 'Audi RSQ8 Mansory')
AddTextEntry('gcram1500', 'Dodge Ram 1500 Custom')
AddTextEntry('spyker', 'Spyker C8')
AddTextEntry('pontiacg8', 'Pontiac G8')
AddTextEntry('x3p720', 'Xpeng P7')
AddTextEntry('mache', 'Ford Mach E')
AddTextEntry('ocnetrongt', 'Audi e-tron GT')
AddTextEntry('f100trophy', 'Ford F100 Trophy')
AddTextEntry('flhxs_streetglide_special18', '2018 Harley Davidson FLHXS')
AddTextEntry('na25', 'Harley Davidson Road King')
AddTextEntry('22Surron', '2022 Sur Ron Lightbee Pxx')
AddTextEntry('buffalo4_USA', 'Bravado Buffalo STX')
AddTextEntry('jubilee_USA', 'Enus Jubilee')
AddTextEntry('deity_USA', 'Enus Deity')
AddTextEntry('cinquemila_USA', 'Lampadati Cinquemila')
AddTextEntry('astron_USA', 'Pfister Astron')
AddTextEntry('iwagen_USA', 'Obey I-Wagen')
AddTextEntry('baller7_USA', 'Gallivanter Baller ST')
AddTextEntry('bcbruiser', 'Dodge 2500')
AddTextEntry('bcys', 'Dodge 3500')
AddTextEntry('bc203500hd', 'Dodge 3500 HD')
AddTextEntry('bcc10c', 'Chevrolet C10')
AddTextEntry('ariant', 'Karin Ariant')
AddTextEntry('asteropers', 'Karin Asteropers')
AddTextEntry('190e', 'Mercedes-Benz 190E Evolution II')
AddTextEntry('gto06', '2006 Pontiac GTO')
AddTextEntry('judge', '1969 Pontiac GTO The Judge')
AddTextEntry('amgh', '1987 Mercedes Benz AMG Hammer Coupe')
AddTextEntry('trans69', '1969 Pontiac Firebird Trans AM')
AddTextEntry('mxpan', '2016 Mazda MX5 Pandem')
-- Custom C Class
AddTextEntry('impala', '1996 Chevrolet Impala SS')
AddTextEntry('impala59c', '1959 Chevrolet Impala')
AddTextEntry('356ac', 'Porsche 356')
AddTextEntry('f15078', '1978 Ford F150')
AddTextEntry('brainshack', '1973 Chevrolet Caprice Nip Donk')
AddTextEntry('cali57', '1957 Ferrari California')
AddTextEntry('trixbox', 'Chevrolet Caprice (Donk)')
AddTextEntry('nova66', 'Chevrolet Nova')
AddTextEntry('galaxie', 'Ford Galaxie')
AddTextEntry('mb300sl', 'Mercedes-Benz 300 SL')
AddTextEntry('mk3', 'Volkswagon Golf (MK3)')
AddTextEntry('porrs73', '1973 Porsche 911')
AddTextEntry('SILV86', '1986 Chevrolet Silverado')
AddTextEntry('tamworth', 'Weeny Tamworth')
AddTextEntry('type262', '1962 Volkswagon Type 2')
AddTextEntry('type263', '1963 Volkswagon Type 2')
AddTextEntry('type266', '1966 Volkswagon Type 2')
AddTextEntry('00f350d', '2000 Ford F350 Dually')
AddTextEntry('H2', 'Hummer H2')
AddTextEntry('granger2_USA', 'Declasse Granger 3600LX')
AddTextEntry('patriot3_USA', 'Mammoth Patriot Mil-Spec')
AddTextEntry('aamx', '1971 AMC Javelin-AMX')
-- Custom D Class
AddTextEntry('fordc32', '1932 Ford V-8 Coupé')
AddTextEntry('80bronco', '1980 Ford Bronco')
AddTextEntry('youga4_USA', 'Bravado Youga Custom')
