local blacklist_entity_hash = {
    'lts_prop_lts_ramp_01',
    'lts_prop_lts_ramp_02',
    'lts_prop_lts_ramp_03',
    'prop_byard_ramp',
    'prop_byard_rampold',
    'prop_byard_rampold_cr',
    'prop_gascyl_ramp_01',
    'prop_gascyl_ramp_door_01',
    'prop_jetski_ramp_01',
    'prop_mp_ramp_01',
    'prop_mp_ramp_01_tu',
    'prop_mp_ramp_02',
    'prop_mp_ramp_02_tu',
    'prop_mp_ramp_03',
    'prop_mp_ramp_03_tu',
    'prop_skate_flatramp',
    'prop_skate_flatramp_cr',
    'prop_water_ramp_01',
    'prop_water_ramp_02',
    'prop_water_ramp_03',
    'v_res_fh_guitaramp',
    'stt_prop_ramp_adj_flip_m',
    'stt_prop_ramp_adj_flip_mb',
    'stt_prop_ramp_adj_flip_s',
    'stt_prop_ramp_adj_flip_sb',
    'stt_prop_ramp_adj_hloop',
    'stt_prop_ramp_adj_loop',
    'stt_prop_ramp_jump_l',
    'stt_prop_ramp_jump_m',
    'stt_prop_ramp_jump_s',
    'stt_prop_ramp_jump_xl',
    'stt_prop_ramp_jump_xs',
    'stt_prop_ramp_jump_xxl',
    'stt_prop_ramp_multi_loop_rb',
    'stt_prop_ramp_spiral_l',
    'stt_prop_ramp_spiral_l_l',
    'stt_prop_ramp_spiral_l_m',
    'stt_prop_ramp_spiral_l_s',
    'stt_prop_ramp_spiral_l_xxl',
    'stt_prop_ramp_spiral_m',
    'stt_prop_ramp_spiral_s',
    'stt_prop_ramp_spiral_xxl',
    'stt_prop_stunt_ramp',
    'stt_prop_stunt_wideramp',
    'stt_prop_stunt_bblock_huge_01',
    'stt_prop_stunt_bblock_huge_02',
    'stt_prop_stunt_bblock_huge_03',
    'stt_prop_stunt_bblock_huge_04',
    'stt_prop_stunt_bblock_huge_05',
    'stt_prop_stunt_bblock_hump_01',
    'stt_prop_stunt_bblock_hump_02',
    'stt_prop_stunt_bblock_lrg1',
    'stt_prop_stunt_bblock_lrg2',
    'stt_prop_stunt_bblock_lrg3',
    'stt_prop_stunt_bblock_mdm1',
    'stt_prop_stunt_bblock_mdm2',
    'stt_prop_stunt_bblock_mdm3',
    'stt_prop_stunt_bblock_qp',
    'stt_prop_stunt_bblock_qp2',
    'stt_prop_stunt_bblock_qp3',
    'stt_prop_stunt_bblock_sml1',
    'stt_prop_stunt_bblock_sml2',
    'stt_prop_stunt_bblock_sml3',
    'stt_prop_stunt_bblock_xl1',
    'stt_prop_stunt_bblock_xl2',
    'stt_prop_stunt_bblock_xl3',
    'stt_prop_stunt_bowling_ball',
    'stt_prop_stunt_bowling_pin',
    'stt_prop_stunt_bowlpin_stand',
    'stt_prop_stunt_domino',
    'stt_prop_stunt_jump15',
    'stt_prop_stunt_jump30',
    'stt_prop_stunt_jump45',
    'stt_prop_stunt_jump_l',
    'stt_prop_stunt_jump_lb',
    'stt_prop_stunt_jump_loop',
    'stt_prop_stunt_jump_m',
    'stt_prop_stunt_jump_mb',
    'stt_prop_stunt_jump_s',
    'stt_prop_stunt_jump_sb',
    'stt_prop_stunt_landing_zone_01',
    'stt_prop_stunt_soccer_ball',
    'stt_prop_stunt_soccer_goal',
    'stt_prop_stunt_soccer_lball',
    'stt_prop_stunt_soccer_sball',
    'stt_prop_stunt_target',
    'stt_prop_stunt_target_small',
    'stt_prop_stunt_track_bumps',
    'stt_prop_stunt_track_cutout',
    'stt_prop_stunt_track_dwlink',
    'stt_prop_stunt_track_dwlink_02',
    'stt_prop_stunt_track_dwsh15',
    'stt_prop_stunt_track_dwshort',
    'stt_prop_stunt_track_dwslope15',
    'stt_prop_stunt_track_dwslope30',
    'stt_prop_stunt_track_dwslope45',
    'stt_prop_stunt_track_dwturn',
    'stt_prop_stunt_track_dwuturn',
    'stt_prop_stunt_track_exshort',
    'stt_prop_stunt_track_fork',
    'stt_prop_stunt_track_funlng',
    'stt_prop_stunt_track_funnel',
    'stt_prop_stunt_track_hill',
    'stt_prop_stunt_track_hill2',
    'stt_prop_stunt_track_jump',
    'stt_prop_stunt_track_link',
    'stt_prop_stunt_track_otake',
    'stt_prop_stunt_track_sh15',
    'stt_prop_stunt_track_sh30',
    'stt_prop_stunt_track_sh45',
    'stt_prop_stunt_track_sh45_a',
    'stt_prop_stunt_track_short',
    'stt_prop_stunt_track_slope15',
    'stt_prop_stunt_track_slope30',
    'stt_prop_stunt_track_slope45',
    'stt_prop_stunt_track_start',
    'stt_prop_stunt_track_start_02',
    'stt_prop_stunt_track_straight',
    'stt_prop_stunt_track_straightice',
    'stt_prop_stunt_track_st_01',
    'stt_prop_stunt_track_st_02',
    'stt_prop_stunt_track_turn',
    'stt_prop_stunt_track_turnice',
    'stt_prop_stunt_track_uturn',
    'stt_prop_stunt_tube_crn',
    'stt_prop_stunt_tube_crn2',
    'stt_prop_stunt_tube_crn_15d',
    'stt_prop_stunt_tube_crn_30d',
    'stt_prop_stunt_tube_crn_5d',
    'stt_prop_stunt_tube_cross',
    'stt_prop_stunt_tube_end',
    'stt_prop_stunt_tube_ent',
    'stt_prop_stunt_tube_fn_01',
    'stt_prop_stunt_tube_fn_02',
    'stt_prop_stunt_tube_fn_03',
    'stt_prop_stunt_tube_fn_04',
    'stt_prop_stunt_tube_fn_05',
    'stt_prop_stunt_tube_fork',
    'stt_prop_stunt_tube_gap_01',
    'stt_prop_stunt_tube_gap_02',
    'stt_prop_stunt_tube_gap_03',
    'stt_prop_stunt_tube_hg',
    'stt_prop_stunt_tube_jmp',
    'stt_prop_stunt_tube_jmp2',
    'stt_prop_stunt_tube_l',
    'stt_prop_stunt_tube_m',
    'stt_prop_stunt_tube_qg',
    'stt_prop_stunt_tube_s',
    'stt_prop_stunt_tube_speed',
    'stt_prop_stunt_tube_speeda',
    'stt_prop_stunt_tube_speedb',
    'stt_prop_stunt_tube_xs',
    'stt_prop_stunt_tube_xxs',
    'imp_prop_flatbed_ramp',
    'gr_prop_gr_ramproof_gate',
    'ar_prop_ar_jetski_ramp.ytd',
    'ar_prop_ar_jetski_ramp_01_dev',
    'des_tankerexplosion_01',
    'des_tankerexplosion_02',
    'hei_prop_carrier_bombs_1',
    'prop_bomb_01',
    'prop_bomb_01_s',
    's_m_y_swat_01',
    'a_c_chimp',
}


local minipunchDiscordID = "<@178016707292561409>"
local WEBHOOK_URL = "https://discordapp.com/api/webhooks/618094411003199509/IeXSWsln5hPo83l5wles9m62kEAKAJQUry6cZvV0MQzCLa6mYgBZOEVdtwwjpC1MUwoh"

AddEventHandler('scrambler:injectionDetected', function(name, source, isServerEvent)
    local eventType = 'client'
    if isServerEvent then
        eventType = 'server'
    end
    local msg = 'Player id [' .. source .. ' / ' .. (GetPlayerIdentifiers(source)[1] or 'N/A') .. '] attempted to use ' .. eventType .. ' event [' .. name .. ']'
    exports.globals:SendDiscordLog(WEBHOOK_URL, msg .. " " .. minipunchDiscordID)
    exports["es_admin"]:BanPlayer(source, "Modding (code injection). If you feel this was a mistake please let a staff member know.")
end)

AddEventHandler("entityCreated",  function(entity)
    for i = 1, #blacklist_entity_hash do
        if DoesEntityExist(entity) then
            if GetEntityModel(entity) == GetHashKey(blacklist_entity_hash[i]) then
                local player = NetworkGetEntityOwner(entity)
                local user = exports["essentialmode"]:getPlayerFromId(player)
                local userGroup = user.getGroup()
                if userGroup == 'user' then
                    exports["es_admin"]:BanPlayer(player, "Modding (object spawning). If you feel this was a mistake please let a staff member know.")
                end
            end
        end
    end
end)
