WEP_EXTENDED_MAG_COMPONENTS = {
    [`WEAPON_HEAVYPISTOL`] = {
        "COMPONENT_HEAVYPISTOL_CLIP_02"
    },
    [`WEAPON_SNSPISTOL`] = {
        "COMPONENT_SNSPISTOL_CLIP_02"
    },
    [`WEAPON_PISTOL`] = {
        "COMPONENT_PISTOL_CLIP_02"
    },
    [`WEAPON_COMBATPISTOL`] = {
        "COMPONENT_COMBATPISTOL_CLIP_02"
    },
    [`WEAPON_PISTOL50`] = {
        "COMPONENT_PISTOL50_CLIP_02"
    },
    [`WEAPON_VINTAGEPISTOL`] = {
        "COMPONENT_VINTAGEPISTOL_CLIP_02"
    },
    [`WEAPON_SMG`] = {
        "COMPONENT_SMG_CLIP_02"
    },
    [`WEAPON_APPISTOL`] = {
        "COMPONENT_AT_PI_FLSH"
    },
    [`WEAPON_MICROSMG`] = {
        "COMPONENT_MICROSMG_CLIP_02"
    },
    [`WEAPON_GUSENBERG`] = {
        "COMPONENT_GUSENBERG_CLIP_02"
    },
    [`WEAPON_ASSAULTRIFLE`] = {
        "COMPONENT_ASSAULTRIFLE_CLIP_02"
    },
    [`WEAPON_CARBINERIFLE`] = {
        "COMPONENT_CARBINERIFLE_CLIP_02"
    },
    [`WEAPON_COMPACTRIFLE`] = {
        "COMPONENT_COMPACTRIFLE_CLIP_02"
    },
    [`WEAPON_MACHINEPISTOL`] = {
        "COMPONENT_MACHINEPISTOL_CLIP_02"
    },
    [`WEAPON_M4GOLDBEAST`] = {
        "COMPONENT_M4GOLDBEAST_CLIP_02",
        "COMPONENT_M4GOLDBEAST_CLIP_03"
    },
    [`WEAPON_SCARSC`] = {
        "COMPONENT_SCARSC_CLIP_03"
    },
    [`WEAPON_AKORUS`] = {
        "COMPONENT_AKORUS_CLIP_02",
        "COMPONENT_AKORUS_CLIP_03"
    }
    
}