module.exports = {
    lintOnSave: false,
    publicPath: './',
    outputDir: '../../files/nui',
    indexPath: 'index.html', //Used to set the storage location of the index.html file generated by the package
};
