local ITEMS = {
    { name = "50 Caliber", type = "weapon", hash = -1716589765, price = 14000, quantity = 1, weight = 20, objectModel = "w_pi_pistol50" },
    { name = "Empty .50 Cal Mag [9]", type = "magazine", price = 400, weight = 7, receives = ".50 Cal", MAX_CAPACITY = 9, currentCapacity = 0 },
    { name = "FN SCAR SC", type = "weapon", hash = GetHashKey("WEAPON_SCARSC"), weight = 28.0, quantity = 1 },
    { name = "Micro SMG", type = "weapon", hash = GetHashKey("WEAPON_MICROSMG"), weight = 25.0, quantity = 1 },
    { name = "Akorus", type = "weapon", hash = GetHashKey("WEAPON_AKORUS"), weight = 25.0, quantity = 1 },
    { name = "M4GoldBeast", type = "weapon", hash = GetHashKey("WEAPON_M4GOLDBEAST"), weight = 30.0, quantity = 1 },
    { name = "Revolver Ultra", type = "weapon", hash = GetHashKey("WEAPON_REVOLVERULTRA"), weight = 25.0, quantity = 1 },
    { name = "Christmas Present", type = "misc", price = 10000, legality = "legal", quantity = 1, weight = 15, objectModel = "hei_prop_heist_box" },
    { name = "Olaf Minigun", type = "weapon", hash = GetHashKey("WEAPON_OLAFMINIGUN"), weight = 30.0, quantity = 1, christmasPresent2022 = true},
    { name = "Noel Launcher", type = "weapon", hash = GetHashKey("WEAPON_NOELLAUNCHER"), weight = 30.0, quantity = 1, christmasPresent2022 = true},
    { name = "Candycrow", type = "weapon", hash = GetHashKey("WEAPON_CANDYCROW"), weight = 15.0, quantity = 1, christmasPresent2022 = true},
    { name = "Batxmas", type = "weapon", hash = GetHashKey("WEAPON_BATXMAS"), weight = 15.0, quantity = 1, christmasPresent2022 = true},
    { name = "Snowhammer", type = "weapon", hash = GetHashKey("WEAPON_SNOWHAMMER"), weight = 25.0, quantity = 1, christmasPresent2022 = true},
    { name = "Up-N-Atomizer", type = "weapon", hash = GetHashKey("WEAPON_RAYPISTOL"), weight = 15.0, quantity = 1},
    { name = "Carbine", type = "weapon", hash = -2084633992, price = tonumber(tostring(math.random(30, 60)) .. "000"), legality = "illegal", quantity = 1, weight = 45, stock = math.random(0, 2), objectModel = "w_ar_carbinerifle" },
    { name = "AP Pistol", type = "weapon", hash = 0x22D8FE39, price = 20000, legality = "illegal", quantity = 1, weight = 15, stock = math.random(0, 2), objectModel = "w_pi_appistol" },
    { name = "Plasma Pistol", type = "weapon", hash = GetHashKey("WEAPON_PLASMAP"), weight = 15.0, quantity = 1 },
    { name = "Heavy Pistol", type = "weapon", hash = -771403250, price = 1500, quantity = 1, weight = 20, objectModel = "w_pi_heavypistol" },
    { name = "Empty Heavy Pistol Extended Mag", quantity = 1, type = "magazine", price = 500, weight = 7, receives = ".45", MAX_CAPACITY = 36, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_HEAVYPISTOL_CLIP_02", compatibleWeapon = GetHashKey("WEAPON_HEAVYPISTOL") },
    { name = "Manual Conversion Kit", type = "mechanicPart", price = 2000, legality = "legal", quantity = 5, weight = 15},
    { name = "Large Firework", type = "misc", price = 2000, legality = "legal", quantity = 5, weight = 15, objectModel = "ind_prop_firework_03" },
    { name = "Firework Gun", type = "weapon", hash = 2138347493, price = 5000, legality = "legal", quantity = 1, weight = 35, objectModel = "w_lr_firework" },
    { name = "Mace", type = "weapon", hash = GetHashKey("WEAPON_MAZE"), price = 5000, legality = "legal", quantity = 1, weight = 15, objectModel = "prop_byard_pipe_01" },
    { name = "Firework Projectile", legality = "legal", type = "ammo", price = 400, weight = 15, quantity = 1 },
    { name = "Vape", price = 400, type = "misc", quantity = 1, legality = "legal", weight = 3, objectModel = "ba_prop_battle_vape_01", blockedInPrison = true},
    { name = "Speaker", price = 5000, legality = "legal", quantity = 1, type = "misc", weight = 20, objectModel = "sm_prop_smug_speaker", doNotAutoRemove = true },
    { name = "Katana", hash = GetHashKey("WEAPON_KATANAS"), type = "weapon", legality = "legal", price = 3000, weight = 10, quantity = 1, objectModel = "w_me_katana_lr"},
    { name = "Ninja Star", type = "weapon", hash = GetHashKey("WEAPON_NINJASTAR"), weight = 5.0, quantity = 1 },
	{ name = "Ninja Star 2", type = "weapon", hash = GetHashKey("WEAPON_NINJASTAR2"), weight = 5.0, quantity = 1 },
    { name = "Rock", type = "weapon", hash = GetHashKey("WEAPON_ROCK"), weight = 5.0, quantity = 1 },
    { name = "Bat", type = "weapon", hash = GetHashKey("WEAPON_BAT"), weight = 15.0, quantity = 1 },
    { name = "The Bleeder", price = 20, type = "food", substance = 60.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_burg1" },
    { name = "Heart Stopper", price = 40, type = "food", substance = 100.0, quantity = 1, legality = "legal", weight = 4, objectModel = "prop_food_burg2" },
    { name = "Foot Long Dog", price = 25, type = "food", substance = 70.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_cs_hotdog_02" },
    { name = "Veggie Gasm Burger", price = 35, type = "food", substance = 85.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_food_burg2" },
    { name = "Torpedo Sandwich", price = 15, type = "food", substance = 55.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_sandwich_01" },
    {name = "Doughnuts", price = 10, type = "food", substance = 25.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_donut_01"},
    {name = "Chicken Nuggets", price = 8, type = "food", substance = 15.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_food_cb_nugets"},
    {name = "Fried Chicken Burger", price = 20, type = "food", substance = 40.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_cb_burg01"},
    {name = "Fries", price = 10, type = "food", substance = 20.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_chips"},
    {name = "Curly Fries", price = 5, type = "food", substance = 12.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_chips"},
    {name = "Pepsi", price = 15, type = "drink", substance = 75.0, quantity = 1, legality = "legal", weight = 1, objectModel = "ng_proc_sodacan_01b"},
    {name = "Orange Fanta", price = 15, type = "drink", substance = 60.0, quantity = 1, legality = "legal", weight = 1, objectModel = "ng_proc_sodacan_01b"},
    {name = "Dr Pepper", price = 15, type = "drink", substance = 70.0, quantity = 1, legality = "legal", weight = 1, objectModel = "ng_proc_sodacan_01b"},
    {name = "Smoothie Special", price = 40, type = "drink", substance = 100.0, quantity = 1, legality = "legal", weight = 1, objectModel = "ng_proc_sodacan_01b"},
    {name = "Orange", price = 5, type = "food", substance = 5.0, quantity = 1, legality = "legal", weight = 2},
    { name = "Filet", type = "tradingCard", src = { front = 'usarrp-filet.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Queen", type = "tradingCard", src = { front = 'usarrp-queen.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Emma", type = "tradingCard", src = { front = 'usarrp-emma.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "357", type = "tradingCard", src = { front = '357.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "AE", type = "tradingCard", src = { front = 'AE.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Amelia", type = "tradingCard", src = { front = 'Amelia.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Arthur", type = "tradingCard", src = { front = 'Arthur.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Baldy", type = "tradingCard", src = { front = 'Baldy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Beebo", type = "tradingCard", src = { front = 'Beebo.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Bella", type = "tradingCard", src = { front = 'Bella1.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Calvin", type = "tradingCard", src = { front = 'Calvin.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Camila", type = "tradingCard", src = { front = 'Camila.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Chang", type = "tradingCard", src = { front = 'Chang2.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Chris", type = "tradingCard", src = { front = 'Chris2.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Chris Cortega", type = "tradingCard", src = { front = 'ChrisCortega.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Chris Mc", type = "tradingCard", src = { front = 'ChrisMC.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Clyde", type = "tradingCard", src = { front = 'Clyde.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Coastal", type = "tradingCard", src = { front = 'Coastal.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Colt", type = "tradingCard", src = { front = 'Colt.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Cyanide", type = "tradingCard", src = { front = 'Cyanide.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Daddy Rick", type = "tradingCard", src = { front = 'DaddyRick.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Damon", type = "tradingCard", src = { front = 'Damon.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Dave", type = "tradingCard", src = { front = 'Dave.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Davies", type = "tradingCard", src = { front = 'Davies.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Denis", type = "tradingCard", src = { front = 'Denis.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Easton", type = "tradingCard", src = { front = 'Easton.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Elliott", type = "tradingCard", src = { front = 'Elliott.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "EMS", type = "tradingCard", src = { front = 'EMS.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Faye n Flint", type = "tradingCard", src = { front = 'Faye_N_Flint.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Forum", type = "tradingCard", src = { front = 'Forum.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Frankies", type = "tradingCard", src = { front = 'Frankies.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Gary", type = "tradingCard", src = { front = 'Gary.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "HH", type = "tradingCard", src = { front = 'HH.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Hugh", type = "tradingCard", src = { front = 'Hugh.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Izzy", type = "tradingCard", src = { front = 'Izzy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Jay", type = "tradingCard", src = { front = 'jAY.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Jim", type = "tradingCard", src = { front = 'Jim.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Johnny", type = "tradingCard", src = { front = 'Johnny.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Jose", type = "tradingCard", src = { front = 'Jose.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Junior", type = "tradingCard", src = { front = 'Junior.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Kacee", type = "tradingCard", src = { front = 'Kacee.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Karen", type = "tradingCard", src = { front = 'Karen.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Knight", type = "tradingCard", src = { front = 'kNIGHT.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Leo", type = "tradingCard", src = { front = 'Leo.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Luke", type = "tradingCard", src = { front = 'Luke.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Morrigan", type = "tradingCard", src = { front = 'Morrigan.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "MPD Ricky", type = "tradingCard", src = { front = 'MPDRicky.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Murphy", type = "tradingCard", src = { front = 'Murphy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Myst", type = "tradingCard", src = { front = 'Myst.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Nessa", type = "tradingCard", src = { front = 'NessaFinal.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Nessa Smile", type = "tradingCard", src = { front = 'NessaSmile.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Nick", type = "tradingCard", src = { front = 'Nick.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Nate", type = "tradingCard", src = { front = 'NNate.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Owgee", type = "tradingCard", src = { front = 'OWGEE_CARD_2.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Prison", type = "tradingCard", src = { front = 'Prison.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Richard", type = "tradingCard", src = { front = 'Richard.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Ricky", type = "tradingCard", src = { front = 'Ricky.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Sammie", type = "tradingCard", src = { front = 'Sammie.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Sammy", type = "tradingCard", src = { front = 'Sammy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Sarah", type = "tradingCard", src = { front = 'Sarah.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Simon", type = "tradingCard", src = { front = 'Simon.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Snow", type = "tradingCard", src = { front = 'Snow.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Stacks", type = "tradingCard", src = { front = 'Stacks.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Tommy", type = "tradingCard", src = { front = 'Tommy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Willy", type = "tradingCard", src = { front = 'Willy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Zack", type = "tradingCard", src = { front = 'Zack.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Zeke", type = "tradingCard", src = { front = 'Zeke.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "SASP", type = "tradingCard", src = { front = 'sasp3.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Alex & Nessa", type = "tradingCard", src = { front = 'AlexNessa.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Phil 160p", type = "tradingCard", src = { front = 'Phil.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Snake", type = "tradingCard", src = { front = 'Snake.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Sykkuno", type = "tradingCard", src = { front = 'Sy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Wong", type = "tradingCard", src = { front = 'Wong.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Alex", type = "tradingCard", src = { front = 'Alex.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Amaree", type = "tradingCard", src = { front = 'Amaree.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Carlos", type = "tradingCard", src = { front = 'Carlos.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Chandler", type = "tradingCard", src = { front = 'Chandler.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Cinco", type = "tradingCard", src = { front = 'Cicno.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Edna", type = "tradingCard", src = { front = 'Edna.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Edna & Chang", type = "tradingCard", src = { front = 'EdnaChang.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Gunz", type = "tradingCard", src = { front = 'Gunz.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Hunter", type = "tradingCard", src = { front = 'Hunter.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Jethro", type = "tradingCard", src = { front = 'jethro.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Justin", type = "tradingCard", src = { front = 'Justin.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Larako", type = "tradingCard", src = { front = 'Larako.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Lyssa", type = "tradingCard", src = { front = 'Lyssa.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Maxwell", type = "tradingCard", src = { front = 'Maxwell.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "N8", type = "tradingCard", src = { front = 'N8.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Olivia", type = "tradingCard", src = { front = 'Olivia.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Oscar", type = "tradingCard", src = { front = 'Oscar.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Outlaws", type = "tradingCard", src = { front = 'outlaws.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Pablo", type = "tradingCard", src = { front = 'pablo.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "PB", type = "tradingCard", src = { front = 'PB.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "The Projects", type = "tradingCard", src = { front = 'Projects.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Pusc", type = "tradingCard", src = { front = 'pusc.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Riley", type = "tradingCard", src = { front = 'Riley.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Ryder", type = "tradingCard", src = { front = 'Ryder.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Sam & Lucy", type = "tradingCard", src = { front = 'SamLucy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Spider", type = "tradingCard", src = { front = 'Spider.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "SWAT", type = "tradingCard", src = { front = 'swat.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Tony", type = "tradingCard", src = { front = 'Tony.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Tyler", type = "tradingCard", src = { front = 'Tyler.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "William", type = "tradingCard", src = { front = 'William.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "James", type = "tradingCard", src = { front = 'James.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Tony 357", type = "tradingCard", src = { front = 'Tony357.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "The Joker", type = "tradingCard", src = { front = 'joker.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Narlee", type = "tradingCard", src = { front = 'narlee.png', back = 'backcard.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Red Eyes B. Dragon", type = "tradingCard", src = { front = 'red-eyes-black-dragon.jpg', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Dark Magician", type = "tradingCard", src = { front = 'dark-magician.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Blue Eyes White Dragon", type = "tradingCard", src = { front = 'blue-eyes-white-dragon.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Dark Magician Girl", type = "tradingCard", src = { front = 'dark-magician-girl.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Exodia Head", type = "tradingCard", src = { front = 'exodia.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Shooting Magestic Star Dragon", type = "tradingCard", src = { front = 'shooting-magestic-star-dragon.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Toon Blue Eyes Dragon", type = "tradingCard", src = { front = 'toon-blue-eye-dragon.png', back = 'yugioh-back.jpg' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Alexander", type = "tradingCard", src = { front = 'Alexander.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Bobby", type = "tradingCard", src = { front = 'Bobby.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Danny", type = "tradingCard", src = { front = 'Danny.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "JHunter", type = "tradingCard", src = { front = 'JHunter.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Lenny", type = "tradingCard", src = { front = 'Lenny.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Lichtenberg", type = "tradingCard", src = { front = 'Lichtenberg.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Luci", type = "tradingCard", src = { front = 'Luci.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Mini", type = "tradingCard", src = { front = 'Mini.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Nancy", type = "tradingCard", src = { front = 'Nancy.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Richard_2", type = "tradingCard", src = { front = 'Richard_2.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "TJ", type = "tradingCard", src = { front = 'TJ.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Tony_2", type = "tradingCard", src = { front = 'Tony_2.png', back = 'usarrp-trading-card-background.png' }, price = 300, weight = 1.0, quantity = 1, notStackable = true, objectModel = "p_ld_id_card_002" },
    { name = "Thermite", legality = "illegal", quantity = 2, type = "misc", weight = 20 },
    { name = "Tablet", price = 1000, type = "misc", quantity = 1, legality = "legal", weight = 3, objectModel = "imp_prop_impexp_tablet", blockedInPrison = true},
    { name = "AK47",hash = GetHashKey("WEAPON_ASSAULTRIFLE"),quantity = 1,type = "weapon",weight = 45,objectModel = "w_ar_assaultrifle",notStackable = true},
    { name = "Combat PDW", hash = GetHashKey("WEAPON_COMBATPDW"), quantity = 1, type = "weapon", weight = 30, objectModel = "w_sb_pdw", notStackable = true},
    { name = "Micro SMG", hash = GetHashKey("WEAPON_MICROSMG"), quantity = 1, type = "weapon", weight = 25, objectModel = "w_sb_microsmg", notStackable = true},
    { name = "SMG", hash = GetHashKey("WEAPON_SMG"), quantity = 1, type = "weapon", weight = 35, objectModel = "w_sb_smg", notStackable = true},
    { name = "Machine Pistol",  hash = GetHashKey("WEAPON_MACHINEPISTOL"),quantity = 1,type = "weapon", weight = 20, objectModel = "w_pi_pistol", notStackable = true},
    { name = "Compact Rifle", hash = GetHashKey("WEAPON_COMPACTRIFLE"), quantity = 1, type = "weapon", weight = 45, notStackable = true},
    { name = "Military Rifle", hash = GetHashKey("WEAPON_MILITARYRIFLE"), quantity = 1, type = "weapon", weight = 45, objectModel = "w_ar_bullpuprifleh4", notStackable = true},
    { name = "Tommy Gun", hash = GetHashKey("WEAPON_GUSENBERG"), quantity = 1, type = "weapon", weight = 45, objectModel = "w_sb_gusenberg", notStackable = true},
    { name = "Assault SMG", hash = GetHashKey("WEAPON_ASSAULTSMG"), quantity = 1, type = "weapon", weight = 40, objectModel = "w_sb_assaultsmg", notStackable = true},
    { name = "Assault Rifle MK2",hash = GetHashKey("WEAPON_ASSAULTRIFLE_MK2"),quantity = 1,type = "weapon",weight = 45,objectModel = "w_ar_assaultrifle",notStackable = true},
    { name = "7.62mm Bullets", type = "ammo", price = 600, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_03" },
    { name = "Empty AK47 Extended Mag", quantity = 1, type = "magazine", price = 500, weight = 7, receives = "7.62mm", MAX_CAPACITY = 60, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_ASSAULTRIFLE_CLIP_02", compatibleWeapon = GetHashKey("WEAPON_ASSAULTRIFLE") },
    { name = "Empty AK47 Drum Mag", quantity = 1, type = "magazine", price = 700, weight = 7, receives = "7.62mm", MAX_CAPACITY = 100, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_ASSAULTRIFLE_CLIP_03", compatibleWeapon = GetHashKey("WEAPON_ASSAULTRIFLE") },
    { name = "12 Gauge Shells", type = "ammo", price = 300, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_02" },
    { name = ".45 Bullets", type = "ammo", price = 375, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_01" },
    { name = "9mm Bullets", type = "ammo", price = 300, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_01" },
    { name = ".50 Cal Bullets", type = "ammo", price = 500, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_01" },
    { name = "9x18mm Bullets", type = "ammo", price = 350, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_01" },
    { name = "5.56mm Bullets", type = "ammo", price = 600, weight = 0.5, quantity = 10, legality = "legal", objectModel = "prop_ld_ammo_pack_03"  },
    { name = "Taser Cartridge", type = "ammo", price = 50, weight = 0.25, quantity = 1 },
    { name = "Stun Gun", type = "weapon", hash = 911657153, price = 400, weight = 5 },
    { name = "Beanbag Shotgun", type = "weapon", hash = GetHashKey("WEAPON_BEANBAGSHOTGUN"), weight = 10 },
    { name = "Beanbag Shell", type = "ammo", price = 300, weight = 0.5, quantity = 8, legality = "legal", objectModel = "prop_ld_ammo_pack_02" },
    { name = "Pistol Parts", price = 3000, type = "weaponParts", weight = 10.0, quantity = 1 },
    { name = "Revolver Kit", price = 4500, type = "weaponParts", weight = 15.0, quantity = 1 },
    { name = "Ceramic Pistol Parts", price = 3200, type = "weaponParts", weight = 10.0, quantity = 1 },
    { name = "Marksman Pistol Parts", price = 3200, type = "weaponParts", weight = 10.0, quantity = 1 },
    { name = "Black Shoe", type = "weapon", hash = GetHashKey("WEAPON_THROWINGSHOEBLACK"), weight = 8.0, quantity = 1 },
    { name = "Red Shoe", type = "weapon", hash = GetHashKey("WEAPON_THROWINGSHOERED"), weight = 8.0, quantity = 1 },
    { name = "Blue Shoe", type = "weapon", hash = GetHashKey("WEAPON_THROWINGSHOEBLUE"), weight = 8.0, quantity = 1 },
    { name = "Rock", type = "weapon", hash = GetHashKey("WEAPON_ROCK"), weight = 5.0, quantity = 1 },
    { name = "Brick", type = "weapon", hash = GetHashKey("WEAPON_BRICK"), weight = 15.0, quantity = 1 },
    { name = "Condoms", price = 5, type = "misc", quantity = 1, legality = "legal", weight = 1, objectModel = "ng_proc_candy01a" },
    { name = "Ceramic Tubing", price = 30, type = "misc", quantity = 5, legality = "legal", weight = 5},
    { name = "Bic Lighter", price = 10, type = "misc", quantity = 1, legality = "legal", weight = 1, objectModel = "prop_cs_pills", blockedInPrison = true},
    { name = "First Aid Kit", price = 100, type = "misc", quantity = 1, legality = "legal", weight = 5, objectModel = "v_ret_ta_firstaid"},
    { name = "IFAK", price = 25, type = "misc", quantity = 1, legality = "legal", weight = 1.0, objectModel = "v_ret_ta_firstaid"},
    { name = "Medical Bag", price = 250, type = "misc", quantity = 1, legality = "legal", weight = 15.0, objectModel = "bkr_prop_duffel_bag_01a"},
    { name = "Large Scissors", price = 15, type = "misc", quantity = 1, legality = "legal", weight = 5, objectModel = "prop_cs_scissors"},
    { name = "Sturdy Rope", price = 100, type = "misc", quantity = 1, legality = "legal", weight = 15, objectModel = "prop_devin_rope_01  "},
    { name = "Bag", price = 100, type = "misc", quantity = 1, legality = "legal", weight = 3, objectModel = "prop_paper_bag_01"},
    { name = 'Hotwiring Kit', type = 'misc', price = 250, legality = 'illegal', quantity = 1, weight = 10 },
    { name = 'Lockpick', type = 'misc', price = 150, legality = 'illegal', quantity = 5, weight = 5 },
    { name = "Large Firework", type = "misc", price = 2000, legality = "illegal", quantity = 1, weight = 25, objectModel = "ind_prop_firework_03" },
    { name = "Aluminum Powder", legality = "legal", quantity = 1, type = "misc", weight = 4.0 },
    { name = "Iron Oxide", legality = "legal", quantity = 5, type = "misc", weight = 8 },
    { name = "Crumpled Paper", type = "misc", quantity = 1, legality = "legal", notStackable = true, weight = 1, objectModel = "prop_paper_ball" },
    { name = "Black Powder", legality = "legal", quantity = 1, type = "misc", weight = 4 },
    { name = "Metal Scraps", legality = "legal", quantity = 1, type = "misc", weight = 8 },
    { name = "Metal Pipe", legality = "legal", quantity = 1, type = "misc", weight = 8 },
    { name = "Gun Powder", legality = "legal", quantity = 1, type = "misc", weight = 5 },
    { name = "Sheet Metal", legality = "legal", quantity = 1, type = "misc", weight = 8 },
    { name = "Metal Spring", legality = "legal", quantity = 1, type = "misc", weight = 2 },
    { name = "7.62mm Shell Casing", legality = "legal", quantity = 2, type = "misc", weight = 0.2 },
    { name = "5.56mm Shell Casing", legality = "legal", quantity = 2, type = "misc", weight = 0.2 },
    { name = "9x18mm Shell Casing", legality = "legal", quantity = 2, type = "misc", weight = 0.2 },
    { name = "Bank Laptop", type = "misc", quantity = 1, legality = "legal", notStackable = true, weight = 10, objectModel = "imp_prop_impexp_tablet"},
    { name = "Blackhat USB Drive", type = "misc", quantity = 1, legality = "illegal", notStackable = true, weight = 1, objectModel = "hei_prop_hst_usb_drive"},
    { name = "Armed Truck Bomb", type = "misc", quantity = 1, legality = "illegal", notStackable = true, weight = 10, objectModel = "prop_ld_bomb"},
    { name = "Crude Oil", legality = "legal", quantity = 1, type = "misc", weight = 15 },
    { name = "Plastic", legality = "legal", quantity = 1, type = "misc", weight = 2 },
    { name = "Copper Wire", legality = "legal", quantity = 1, type = "misc", weight = 3 },
    { name = "M4GoldBeast Gun Cast", legality = "legal", quanity = 1, type = "misc", weight = 10},
    { name = "Empty M4GoldBeast Mag", quantity = 1, type = "magazine", price = 800, weight = 7, receives = "7.62mm", MAX_CAPACITY = 30, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_M4GOLDBEAST_CLIP_01", compatibleWeapon = GetHashKey("WEAPON_M4GOLDBEAST") },
    { name = "Empty M4GoldBeast Extended Mag", quantity = 1, type = "magazine", price = 950, weight = 7, receives = "7.62mm", MAX_CAPACITY = 60, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_M4GOLDBEAST_CLIP_02", compatibleWeapon = GetHashKey("WEAPON_M4GOLDBEAST") },
    { name = "Empty M4GoldBeast Drum Mag", quantity = 1, type = "magazine", price = 1300, weight = 7, receives = "7.62mm", MAX_CAPACITY = 120, currentCapacity = 0, legality = "illegal", notStackable = true, magComponent = "COMPONENT_M4GOLDBEAST_CLIP_03", compatibleWeapon = GetHashKey("WEAPON_M4GOLDBEAST") },
    {
        name = "Wheelchair",
        price = 200,
        type = "misc",
        quantity = 1,
        legality = "legal",
        weight = 30,
        objectModel = "prop_wheelchair_01",
        invisibleWhenDropped = true
    },
    {
        name = "Stretcher",
        price = 400,
        type = "misc",
        quantity = 1,
        legality = "legal",
        weight = 40,
        objectModel = "prop_ld_binbag_01",
        invisibleWhenDropped = true
    },
    { name = "Magic Potion", type = "magicPotion", quantity = 1, weight = 5, christmasPresent2022 = true},
    { name = "Hawk Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_chickenhawk"},
    { name = "Chimp Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_chimp"},
    { name = "Cormorant Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_cormorant"},
    { name = "Cow Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_cow"},
    { name = "Coyote Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_coyote"},
    { name = "Crow Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_crow"},
    { name = "Deer Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_deer"},
    { name = "Hen Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_hen"},
    { name = "Cat Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_cat_01"},
    { name = "Boar Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_boar"},
    { name = "Pig Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_pig"},
    { name = "Pigeon Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_pigeon"},
    { name = "Poodle Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_poodle"},
    { name = "Pug Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_pug"},
    { name = "Rabbit Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_rabbit_01"},
    { name = "Rat Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_rat"},
    { name = "Seagull Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_seagull"},
    { name = "Westy Potion", type = "magicPotion", quantity = 1, weight = 5, model = "a_c_westy"},
    { name = "Low Grip Tires", price = 5000, type = "mechanicPart", quantity = 1, weight = 50, objectModel = "prop_wheel_03"},
    { name = "Normal Tires", price = 5000, type = "mechanicPart", quantity = 1, weight = 50, objectModel = "prop_wheel_03"},
    { name = "Underglow Kit", price = 5000, type = "mechanicPart", quantity = 1, weight = 30},
    { name = "Pseudoephedrine",legality = "illegal",quantity = 1,type = "chemical",weight = 5,objectModel = "bkr_prop_meth_acetone"},
    { name = "Red Phosphorus",legality = "illegal",quantity = 1,type = "chemical",weight = 5,objectModel = "bkr_prop_meth_ammonia"},
    { name = "Xenon Headlights",price = 5000,quantity = 1,weight = 30,type = "mechanicPart"},
    { name = "Stage 1 Brakes", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Stage 2 Brakes", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Tint Remover", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "5% Window Tint", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "20% Window Tint", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "35% Window Tint", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Stage 1 Transmission", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Stage 2 Transmission", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    {
		name = "Turbo",
		price = 10000,
		quantity = 1,
		weight = 30,
		type = "mechanicPart"
	},
    {
		name = "20% Armor",
		price = 12000,
		quantity = 1,
		weight = 50,
		type = "mechanicPart"
	},
    { name = "Stage 1 Intake", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Stage 2 Intake", price = 5000, type = "mechanicPart", quantity = 1, weight = 10},
    { name = "Fruit Tart", price = 20, type = "food", substance = 40.0, quantity = 1, legality = "legal", weight = 1, objectModel = "prop_food_burg1"},
    { name = "Pancake", price = 40, type = "food", substance = 45.0, quantity = 1, legality = "legal", weight = 1, objectModel = "prop_food_burg2"},
    { name = "Miso Soup", price = 40, type = "food", substance = 50.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_food_burg2"},
    { name = "UWU Sandwich", price = 40, type = "food", substance = 45.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_burg2"},
    { name = "Weepy Cupcake", price = 55, type = "food", substance = 65.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_burg2"},
    { name = "Senpai Combo", price = 120, type = "food", substance = 100.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_donut_01"},
    { name = "Buddha Bowl", price = 75, type = "food", substance = 85.0, quantity = 1, legality = "legal", weight = 2, objectModel = "prop_food_cb_nugets"},
    { name = "Bento Box", price = 95, type = "food", substance = 100.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_food_cb_nugets"},
    { name = "Mini Licious Box", price = 95, type = "food", substance = 85.0, quantity = 1, legality = "legal", weight = 3, objectModel = "prop_food_cb_nugets"},
    { name = "Coffee", price = 7, type = "drink", substance = 45.0, quantity = 1, legality = "legal", weight = 1, objectModel = "p_amb_coffeecup_01"},
    { name = "Espresso", price = 10, type = "drink", substance = 55.0, quantity = 1, legality = "legal", weight = 1, objectModel = "p_amb_coffeecup_01"},
    { name = "Macchiato", price = 15, type = "drink", substance = 60.0, quantity = 1, legality = "legal", weight = 1, objectModel = "v_res_mcofcup"},
    { name = "Latte", price = 25, type = "drink", substance = 85.0, quantity = 1, legality = "legal", weight = 1, objectModel = "v_res_mcofcup"},
    { name = "Mocha", price = 40, type = "drink", substance = 80.0, quantity = 1, legality = "legal", weight = 2, objectModel = "v_res_mcofcup"},
    { name = "Alex's Special", price = 50, type = "drink", substance = 75.0, quantity = 1, legality = "legal", weight = 2, objectModel = "v_res_mcofcup"},
    { name = "Blueberry Bubble Tea", price = 20, type = "drink", substance = 45.0, quantity = 1, legality = "legal", weight = 1, objectModel = "p_amb_coffeecup_01"},
    { name = "Mint Bubble Tea", price = 20, type = "drink", substance = 45.0, quantity = 1, legality = "legal", weight = 1, objectModel = "p_amb_coffeecup_01"},
    { name = "Rose Bubble Tea", price = 20, type = "drink", substance = 45.0, quantity = 1, legality = "legal", weight = 1, objectModel = "p_amb_coffeecup_01"},
    { name = "Rainbow Glitter Frappuccino", price = 20, type = "drink", substance = 65.0, quantity = 1, legality = "legal", weight = 2, objectModel = "p_amb_coffeecup_01"},
    { name = "Battering Ram", type = "misc", price = 250, weight = 25, quantity = 1 },
    {name = "Repair Kit",
    price = 2000,
    quantity = 1,
    weight = 10,
    type = "misc",
    notStackable = true},
    { name = "Empty 7.62mm Mag [30]", type = "magazine", price = 150, weight = 5, receives = "7.62mm", MAX_CAPACITY = 30, currentCapacity = 0, objectModel = "w_ar_carbinerifle_mag1" },
}


for i = 1, #ITEMS do
    if ITEMS[i].type and ITEMS[i].type == "weapon" then
        ITEMS[i].notStackable = true
    end
end

exports("getItem", function(name)
    for i = 1, #ITEMS do
        if ITEMS[i].name == name then
            return json.decode(json.encode(ITEMS[i]))
        end
    end
end)

exports("getItemWithFieldVal", function(name, field, val)
    for i = 1, #ITEMS do
        if ITEMS[i].name == name then
            if ITEMS[i][field] and ITEMS[i][field] == val then
                return json.decode(json.encode(ITEMS[i]))
            end
        end
    end
end)

exports("getAllItemsByFieldVal", function(field, val)
    local ret = {}
    for i = 1, #ITEMS do
        if ITEMS[i][field] and ITEMS[i][field] == val then
            local itemCopy = json.decode(json.encode(ITEMS[i]))
            table.insert(ret, itemCopy)
        end
    end
    return ret
end)
