-- Edit the table below for more loadouts!
LOADOUTS =  {
    ["cop"] = {
        name = "Cop",
        permission_level = 0,
        weapons = { "WEAPON_COMBATPISTOL", "WEAPON_STUNGUN", "WEAPON_NIGHTSTICK", "WEAPON_PUMPSHOTGUN", "WEAPON_FLAREGUN", "WEAPON_FLASHLIGHT", "WEAPON_FIREEXTINGUISHER" },
        skins = { "s_m_y_cop_01", "s_f_y_cop_01" }
    },
	["sheriff"] = {
		name = "Sheriff",
		permission_level = 0,
		weapons = { "WEAPON_COMBATPISTOL", "WEAPON_STUNGUN", "WEAPON_NIGHTSTICK", "WEAPON_PUMPSHOTGUN", "WEAPON_FLAREGUN", "WEAPON_FLASHLIGHT", "WEAPON_FIREEXTINGUISHER" },
		skins = { "S_M_Y_Sheriff_01", "S_F_Y_Sheriff_01" }
	},
	["highwaypatrol"] = {
		name = "Highway Patrol",
		permission_level = 0,
		weapons = { "WEAPON_COMBATPISTOL", "WEAPON_STUNGUN", "WEAPON_NIGHTSTICK", "WEAPON_PUMPSHOTGUN", "WEAPON_FLAREGUN", "WEAPON_FLASHLIGHT", "WEAPON_FIREEXTINGUISHER" },
		skins = { "s_m_y_hwaycop_01" }
	},
	["ems"] = {
		name = "EMS",
		permission_level = 0,
		weapons = { "WEAPON_FLASHLIGHT", "WEAPON_FIREEXTINGUISHER" },
		skins = { "S_M_M_Paramedic_01" }
	},
	["fire"] = {
		name = "Fire Rescue",
		permission_level = 0,
		weapons = { "WEAPON_FLASHLIGHT", "WEAPON_FIREEXTINGUISHER" },
		skins = { "S_M_Y_Fireman_01" }
	},
    ["civ"] = {
        name = "Civilian",
		permission_level = 0,
        weapons = { },
        skins = {"a_m_y_skater_01",
            "a_m_y_skater_02",
            "a_m_m_beach_01",
            "a_m_m_bevhills_01",
            "a_m_m_bevhills_02",
            "a_m_m_business_01",
            "a_m_m_eastsa_01",
            "a_m_m_eastsa_02",
            "a_m_m_farmer_01",
            "a_m_m_genfat_01",
            "a_m_m_golfer_01",
            "a_m_m_hillbilly_01",
            "a_m_m_indian_01",
            "a_m_m_mexcntry_01",
            "a_m_m_paparazzi_01",
            "a_m_m_tramp_01",
            "a_m_y_hiker_01",
            "a_m_y_hippy_01",
            "a_m_y_genstreet_01",
            "a_m_m_socenlat_01",
            "a_m_m_og_boss_01",
            "a_f_y_tourist_02",
            "a_f_y_tourist_01",
            "a_f_y_soucent_01",
            "a_f_y_scdressy_01",
            "a_m_y_cyclist_01",
            "a_m_y_golfer_01",
			"S_M_M_Linecook",
			"S_M_Y_Barman_01",
			"S_M_Y_BusBoy_01",
			"S_M_Y_Waiter_01",
			"A_M_Y_StBla_01",
			"A_M_M_Tennis_01",
			"A_M_Y_BreakDance_01",
			"A_M_Y_SouCent_03",
			"S_M_M_Bouncer_01",
			"S_M_Y_Doorman_01",
			"A_F_M_Tramp_01",
			"A_F_M_Skidrow_01",
			"A_M_Y_Downtown_01",
			"S_M_M_Gardener_01",
			"A_M_M_Business_01",
			"A_M_Y_StWhi_01",
			"A_F_Y_Hipster_02",
			"A_M_M_Hillbilly_02",
			"S_M_O_Busker_01",
			"S_M_M_Security_01",
			"A_M_M_Paparazzi_01",
			"S_M_Y_PestCont_01",
			"A_M_M_Malibu_01",
			"A_M_M_Polynesian_01",
			"A_M_Y_VinDouche_01"			
        }
    }
}
