AddEventHandler("playerSpawned", function(spawn)
    TriggerEvent("chatMessage", "", { 0, 0, 0 }, "^0Welcome to ^1U^0S^5A ^3REALISM RP^0!")
	TriggerEvent("chatMessage", "", { 0, 0, 0 }, "^0Type ^3'/info' ^0for more information!")
    TriggerEvent("chatMessage", "", { 0, 0, 0 }, "^0Press ^3'F1' ^0to open the interaction menu.")
end)
