function getPlayerIdentifier(playerId)
    local char = exports["usa-characters"]:GetCharacter(playerId)
    return (char.get("_id") or nil)
end

function getPlayerMoney(playerId)
    local char = exports["usa-characters"]:GetCharacter(playerId)
    return char.get("bank")
end

function removePlayerMoney(playerId, amount)
    local char = exports["usa-characters"]:GetCharacter(playerId)
    char.set("bank", char.get("bank") - amount)
    TriggerClientEvent("usa:notify",playerId, "$"..amount.." has been ~r~removed~w~ from your bank account.")
end

function givePlayerMoney(playerId, amount)
    local char = exports["usa-characters"]:GetCharacter(playerId)
    char.set("bank", char.get("bank") + amount)
    TriggerClientEvent("usa:notify",playerId, "$"..amount.." has been ~g~added~w~ to your bank account.")
end

-- SERVER export - This function is exported, so it can be opened from any other server-side script by using 'exports['rahe-racing']:openRacingTablet(source)'
function openRacingTablet(playerId)
    TriggerClientEvent('rahe-racing:client:openTablet', playerId)
end

function notifyPlayer(playerId, message)
    TriggerClientEvent('chatMessage', playerId, "SERVER", "normal", message)
end

-- You can use the function provided here, or use your own existing logic
function getVehicleClassFromHash(modelHash)
    return getVehicleClassFromHash(modelHash)
end

function getVehicleClassFromHash(modelHash)
    for _, v in ipairs(supportedVehicles) do
        if GetHashKey(v.model) == modelHash then
            return v.class
        end
    end

    -- Returns 'C' class for a vehicle when a class wasn't found for it
    return 'C'
end

-- Debug Stuff below
-- TriggerEvent('es:addCommand', "carclass", function(source, args, char)
--     local vehicle = GetVehiclePedIsIn(GetPlayerPed(source), false)
--     local model = GetEntityModel(vehicle)
--     local myClass = getVehicleClassFromHash(model)
--     notifyPlayer(source, "This vehicle is ".. model .. " and is a " .. myClass .. " class.")
-- end, { help = "Get Racing Items - TESTING PURPOSES" })

-- -- Testing Phase
-- TriggerEvent('es:addCommand', 'raceitems', function(source, args, char)
--     local char = exports["usa-characters"]:GetCharacter(source)
--     local itemOne = { name = "Racing Dongle", type = "misc",  quantity = 1,  legality = "legal",  weight = 1,  objectModel = "hei_prop_hst_usb_drive" }
--     local itemTwo = { name = "Tablet", type = "misc",  quantity = 1,  legality = "legal",  weight = 3,  objectModel = "imp_prop_impexp_tablet" }
--     char.giveItem(itemOne)
--     char.giveItem(itemTwo)
-- end, { help = "Get Racing Items - TESTING PURPOSES" })

-- Feel free to add your own vehicles here. Most of the default cars are here, modded cars have to be added!
supportedVehicles = {
    -- Df Class:*
    { name = "Declasse Drift Tampa", model = "tampa2", class = "V"},
    -- CUSTOM- Df Class
    { name = "Mazda Miata", model = "na6", class = "Df" },
    { name = "Nissan 240SX", model = "rmod240sx", class = "Df" },
    { name = "Nissan 240SX (s14)", model = "silvia3", class = "Df" },
    { name = "Nissan S15", model = "s15yoshio", class = "Df" },
    { name = "Mitsubishi EVO IX", model = "evoix", class = "Df" },
    { name = "Toyota Chaser", model = "razerchaser", class = "Df" },
    { name = "1982 Datsun Bluebird 910 SSS", model = "datsun910", class = "Df" },
    { name = "1985 Toyota Sprinter Trueno GT Apex (AE86)", model = "ae86", class = "Df" },
    { name = "Chevorlet Corvette C6", model = "GODzC6FD", class = "Df" },
    { name = "Chevorlet Corvette C6 RC", model = "GODzC6FD_RC", class = "Df" },
    { name = "Ford Mustang", model = "bugfd", class = "Df" },
    -- Event Class:**
    { name = "Formula", model = "formula", class = "DD" },
    { name = "Formula", model = "formula2", class = "DD" },
    { name = "Benefactor BR8", model = "openwheel1", class = "DD" },
    { name = "Benefactor BR8", model = "openwheel2", class = "DD" },
    { name = "1975 Ferrari 312T2", model = "312t2", class = "DD" },
    { name = "2022 Red Bull RB18", model = "rb18", class = "DD" },
    { name = "Bruiser", model = "bruiser", class = "DD" },
    { name = "Bruiser", model = "bruiser2", class = "DD" },
    { name = "Bruiser", model = "bruiser3", class = "DD" },
    { name = "Bruiser", model = "bruiser4", class = "DD" },
    { name = "Brutus", model = "brutus3", class = "DD" },
    { name = "Dominator", model = "dominator4", class = "DD" },
    { name = "Dominator", model = "dominator6", class = "DD" },
    { name = "Issi", model = "issi4", class = "DD" },
    { name = "Issi", model = "issi5", class = "DD" },
    { name = "Issi", model = "issi6", class = "DD" },
    { name = "Impaler", model = "impaler4", class = "DD" },
    { name = "Monster", model = "monster3", class = "DD" },
    { name = "Monster", model = "monster4", class = "DD" },
    { name = "Monster", model = "monster5", class = "DD" },
    { name = "Slamvan", model = "slamvan6", class = "DD" },
    { name = "Cerebus", model = "cerebus2", class = "DD" },
    { name = "Cerebus", model = "cerebus3", class = "DD" },
    { name = "BMW E36", model = "PV_bmwe36", class = "DD" },
    { name = "Bugatti La Voiture Noire", model = "PV_bugatti", class = "DD" },
    { name = "Bugatti Veyron", model = "PV_bugvr", class = "DD" },
    { name = "Rolls Royce Dawn", model = "PV_dawn", class = "DD" },
    { name = "Nissan GTR", model = "PV_gtr", class = "DD" },
    { name = "Jeep Wrangler", model = "PV_jeep", class = "DD" },
    { name = "Lamborghini Gallardo", model = "PV_lgss", class = "DD" },
    { name = "Range Rover", model = "PV_rover", class = "DD" },
    { name = "Lamborghini Sian", model = "PV_sianr", class = "DD" },
    { name = "Lamborghini Urus", model = "PV_urus", class = "DD" },
    -- X Class:**
    { name = "Truffade Adder", model = "adder", class = "X" },
    { name = "Truffade Nero", model = "nero", class = "X" },
    { name = "Truffade Nero (Custom)", model = "nero2", class = "X" },
    { name = "Truffade Thrax", model = "thrax", class = "X" },
    { name = "Benefactor LM87", model = "lm87", class = "X" },
    { name = "Overflod Entity MT", model = "entity3", class = "X" },
    -- CUSTOM- X Class:
    { name = "2011 Bugatti Veyron Super Sport", model = "supersport", class = "X" },
    { name = "2017 Koenigsegg Agera RS", model = "agerars", class = "X" },
    { name = "Koenigsegg Jesko", model = "rmodjesko", class = "X" },
    { name = "Bugatti Bolide", model = "bolide", class = "X" },
    { name = "Bugatti Chiron", model = "chiron", class = "X" },
    { name = "Porsche GT1", model = "gt1", class = "X" },
    -- S Class:**
    { name = "Lampadati Tigon", model = "tigon", class = "S" },
    { name = "Pfister 811", model = "pfister811", class = "S" },
    { name = "Pegassi Vacca", model = "vacca", class = "S" },
    { name = "Progen T20", model = "t20", class = "S" },
    { name = "Pegassi Osiris", model = "osiris", class = "S" },
    { name = "Progen GP1", model = "gp1", class = "S" },
    { name = "Pegassi Reaper", model = "reaper", class = "S" },
    { name = "Pegassi Tempesta", model = "tempesta", class = "S" },
    { name = "Vapid FMJ", model = "FMJ", class = "S" },
    { name = "Progen Tyrus", model = "tyrus", class = "S" },
    { name = "Annis LE7B", model = "lE7B", class = "S" },
    { name = "Overflod Tyrant", model = "tyrant", class = "S" },
    { name = "Overflod Zeno", model = "zeno_USA", class = "S" },
    { name = "Pegassi Tezeract", model = "tezeract", class = "E" }, -- ELECTRIC
    { name = "Grotti Visione", model = "visione", class = "S" },
    { name = "Pegassi Zorrusso", model = "zorrusso", class = "S" },
    { name = "Dewbauchee Vagner", model = "vagner", class = "S" },
    { name = "Principe Deveste Eight", model = "deveste", class = "S" },
    { name = "Overflod Entity XXR", model = "entity2", class = "S" },
    { name = "Progen Emerus", model = "emerus", class = "S" },
    { name = "Benefactor Krieger", model = "krieger", class = "S" },
    { name = "Grotti Cheetah", model = "cheetah", class = "S" },
    { name = "Grotti Cheetah Classic", model = "cheetah2", class = "S" },
    { name = "Grotti Furia", model = "furia", class = "S" },
    { name = "Grotti Turismo Classic", model = "turismo2", class = "S" },
    { name = "Pegassi Infernus", model = "infernus", class = "S" },
    { name = "Pegassi Infernus Classic", model = "infernus2", class = "S" },
    { name = "Pegassi Torero", model = "torero", class = "S" },
    { name = "Pegassi Ignus", model = "ignus_USA", class = "S" },
    { name = "Dewbauchee Champion", model = "champion_USA", class = "S" },
    { name = "Benefactor Schlagen", model = "schlagen", class = "S" },
    { name = "Pegassi Zentorno", model = "zentorno", class = "S" },
    { name = "Grotti Itali GTB", model = "italigtb", class = "S" },
    { name = "Grotti Itali GTB Custom", model = "italigtb2", class = "S" },
    { name = "Grotti Itali GTO", model = "italigto", class = "S" },
    { name = "Ocelot XA-21", model = "xa21", class = "S" },
    { name = "Ubermacht SC1", model = "sc1", class = "S" },
    { name = "Ocelot Penetrator", model = "penetrator", class = "S" },
    { name = "Grotti Turismo R", model = "turismor", class = "S" },
    { name = "Obey 9F", model = "ninef", class = "S" },
    { name = "Obey 9F Cabrio", model = "ninef2", class = "S" },
    { name = "Pfister Comet SR", model = "comet5", class = "S" },
    { name = "Pfister Comet S2", model = "comet6", class = "S" },
    { name = "Pfister Comet S2 Cabrio", model = "comet7_USA", class = "S" },
    { name = "Pfister Growler", model = "growler", class = "S" },
    { name = "Lampadati Corsita", model = "corsito", class = "S" },
    { name = "Benefactor SM722", model = "sm722", class = "S" },
    { name = "Obey 10F", model = "tenf", class = "S" },
    { name = "Obey 10F Widebody", model = "tenf2", class = "S" },
    { name = "Pegassi Torero XO", model = "torero2", class = "S" },
    { name = "Karin Hotring Everon", model = "everon2", class = "S" },
    -- CUSTOM- S Class:
    { name = "1999 Lamborghini Diablo GTR", model = "500gtrlam", class = "S" },
    { name = "Mclaren 600LT", model = "600lt", class = "S" },
    { name = "Ferrari F8 Tributo", model = "f8t", class = "S" },
    { name = "Lamborghini LP700 R", model = "lp700r", class = "S" },
    { name = "Nissan GTR", model = "gtr", class = "S" },
    { name = "Audi R8", model = "r820", class = "S" },
    { name = "2010 Lexus LFA", model = "lfa", class = "S" },
    { name = "Lamborghini Huracan", model = "lwhuracan", class = "S" },
    { name = "Ferrari F12", model = "rmodf12tdf", class = "S" },
    { name = "Ferrari F40", model = "rmodf40", class = "S" },
    { name = "Italdesign Nissan GTR-50", model = "rmodgtr50", class = "S" },
    { name = "Lamborghini Sian", model = "rmodsianr", class = "S" },
    { name = "BMW I8", model = "I8", class = "E" }, -- ELECTRIC
    { name = "Porsche 911 Turbo S", model = "pts21", class = "S" },
    { name = "Porsche GT3", model = "pgt3", class = "S" },
    { name = "2020 Tesla Roadster", model = "tesroad20", class = "S" },
    { name = "Lamborghini Terzo Millennio", model = "ocnlamtmc", class = "E" }, -- ELECTRIC
    { name = "Lotus Evija", model = "evija", class = "E" }, -- ELECTRIC
    { name = "2016 Honda NSX", model = "aimgainnsx", class = "S" },
    { name = "McLaren Elva", model = "elva", class = "S" },
    { name = "Lamborghini Huracan Evo 2", model = "evo2", class = "S" },
    { name = "Lamborghini Gallardo LW", model = "gallardolw", class = "S" },
    { name = "Lamborghini Murcielago LP-670", model = "lp670", class = "S" },
    { name = "Lamborghini Murcielago LP-670 LW", model = "lwlp670", class = "S" },
    { name = "Ferrari 458 LW", model = "lw458s", class = "S" },
    { name = "Jaguar CX-75", model = "cx75", class = "S" },
    { name = "Lamborghini Essenza", model = "rmodessenza", class = "S" },
    { name = "Mercedes SLR Stirling Moss", model = "moss", class = "S" },
    { name = "Ford GT500" , model = "shelby20", class = "S" },
    { name = "Mercedes-Benz AMG GT" , model = "rr20amggt", class = "S" },
    { name = "Dodge Charger (Redeye)" , model = "chr20" , class = "S" },
    { name = "Lamborghini Urus", model = "urustc", class = "S" },
    { name = "Audi RSQ8 Mansory", model = "rsq8m", class = "S" },
    { name = "2022 Porsche GT3", model = "pgt322", class = "S" },
    { name = "Honda Civic (EG6)", model = "eg6", class = "S" },
    { name = "Honda Civic (EK9)", model = "spoonek", class = "S" },
    { name = "1993 Honda Civic (FnF)", model = "fnfcivic", class = "S" },
    { name = "Pegassi Monroe Custom", model = "monroec", class = "S" },
    { name = "Mclaren Senna", model = "sennas", class = "S" },
    { name = "Mclaren Senna GTR", model = "sennasgtr", class = "S" },
    { name = "Pagani Zonda R", model = "zondar", class = "S" },
    { name = "Ferrari FXXK", model = "fxxk", class = "S" },
    { name = "Mercedes-Benz CLK LM", model = "clklm", class = "S" },
    { name = "Toyota Supra (Castrol)", model = "castrolsupra", class = "S" },
    { name = "Nissan Skyline GT-R (R34)", model = "skyline", class = "S" },
    { name = "Nissan Skyline GT-R V-Spec (R33)", model = "r33vspec", class = "S" },
    { name = "Nissan Skyline GT-R (R32)", model = "r32", class = "S" },
    { name = "1992 Honda NSX", model = "na1", class = "S" },
    { name = "Ferrari LaFerrari", model = "laferrari", class = "S" },
    { name = "McLaren P1", model = "p1", class = "S" },
    { name = "Porsche 918", model = "918", class = "S" },
    { name = "McLaren P1 GTR", model = "rmodp1gtr", class = "S" },
    { name = "2020 Porsche 718 Cayman GT4", model = "por718gt4", class = "S" },
    { name = "Chevrolet Corvette C7R GTLM", model = "C7R", class = "S" },
    { name = "2012 Porsche 911 GT2 RS", model = "pgt2", class = "S" },
    { name = "1993 Porsche 911 (993) RWB "Rotana"", model = "911rwb", class = "S" },
    { name = "2016 SRT Viper", model = "viper", class = "S" },
    { name = "2016 SRT Viper ACR", model = "acr", class = "S" },
    { name = "Audi R8 Hycade", model = "r8hycade", class = "S" },
    { name = "BMW M8 GTE", model = "rmodm8gte", class = "S" },
    -- A Class:**
    { name = "Sultan RS", model = "sultanrs", class = "A" },
    { name = "Annis Elegy Retro", model = "elegy", class = "A" },
    { name = "Bravado Banshee 900R", model = "banshee2", class = "A" },
    { name = "Schyster Deviant", model = "deviant", class = "A" },
    { name = "Pegassi Toros", model = "toros", class = "A" },
    { name = "Ubermacht Cypher", model = "cypher", class = "A" },
    { name = "Primo ARD", model = "primoard", class = "A" },
    { name = "Emperor SHEAVA", model = "sheava", class = "A" },
    { name = "Overflod Autarch", model = "autarch", class = "A" },
    { name = "Bravado Banshee", model = "banshee", class = "A" },
    { name = "Invetero Coquette", model = "coquette", class = "A" },
    { name = "Invetero Coquette D10", model = "coquette4", class = "A" },
    { name = "Albany Alpha", model = "alpha", class = "A" },
    { name = "Grotti Bestia GTS", model = "bestiagts", class = "A" },
    { name = "Grotti Carbonizzare", model = "carbonizzare", class = "A" },
    { name = "Pfister Comet", model = "comet2", class = "A" },
    { name = "Pfister Comet Retro", model = "comet3", class = "A" },
    { name = "Dinka Jester Retro", model = "jester3", class = "A" },
    { name = "Dinka Jester RR", model = "jester4", class = "A" },
    { name = "Annis Elegy RH8", model = "elegy2", class = "A" },
    { name = "Benefactor Feltzer", model = "feltzer2", class = "A" },
    { name = "Lampadati Furore GT", model = "furoregt", class = "A" },
    { name = "Dinka Jester", model = "jester", class = "A" },
    { name = "Ocelot Jugular", model = "jugular", class = "A" },
    { name = "Emperor Vectre", model = "vectre", class = "A" },
    { name = "Vapid Bullet", model = "bullet", class = "A" },
    { name = "Dewbauchee Massacro", model = "massacro", class = "A" },
    { name = "Ocelot Pariah", model = "pariah", class = "A" },
    { name = "Maibatsu Penumbra", model = "penumbra", class = "A" },
    { name = "Dewbauchee Rapid GT", model = "rapidgt", class = "A" },
    { name = "Dewbauchee Rapid GT Cabrio", model = "rapidgt2", class = "A" },
    { name = "Hijak Ruston", model = "ruston", class = "A" },
    { name = "Benefactor Schwartzer", model = "schwarzer", class = "A" },
    { name = "Dewbauchee Seven-70", model = "seven70", class = "A" },
    { name = "Dewbauchee Specter", model = "specter", class = "A" },
    { name = "Dewbauchee Specter Custom", model = "specter2", class = "A" },
    { name = "Benefactor Surano", model = "surano", class = "A" },
    { name = "Karin 190z", model = "z190", class = "A" },
    { name = "Enus Cognoscenti Cabrio", model = "cogcabrio", class = "A" },
    { name = "Ocelot F620", model = "f620", class = "A" },
    { name = "Lampadati Felon GT", model = "felon2", class = "A" },
    { name = "Obey Tailgater A", model = "tailgater2", class = "B" },
    { name = "Ubermacht Zion", model = "zion", class = "A" },
    { name = "Ubermacht Zion Cabrio", model = "zion2", class = "A" },
    { name = "Enus Paragon", model = "paragon", class = "A" },
    { name = "Enus Windsor", model = "windsor", class = "A" },
    { name = "Grotti Brioso R/A", model = "brioso", class = "A" },
    { name = "Coil Voltic", model = "voltic", class = "E" }, -- ELECTRIC
    { name = "Vapid Dominator", model = "dominator", class = "A" },
    { name = "Vapid Dominator GTX", model = "dominator3", class = "A" },
    { name = "Vapid Dominator ASP", model = "dominator7", class = "A" },
    { name = "Vapid Dominator GTT", model = "dominator8", class = "A" },
    { name = "Bravado Gauntlet", model = "gauntlet", class = "A" },
    { name = "Bravado Gauntlet Hellfire", model = "gauntlet4", class = "A" },
    { name = "Declasse Vigero ZX", model = "vigero2", class = "A" },
    { name = "Enus Stafford", model = "stafford", class = "A" },
    { name = "Vapid Blade", model = "blade", class = "A" },
    { name = "Imponte Dukes", model = "dukes", class = "A" },
    { name = "Declasse Vamos", model = "vamos", class = "A" },
    { name = "Vapid Ellie", model = "ellie", class = "A" },
    { name = "Imponte Ruiner", model = "ruiner", class = "A" },
    { name = "Declasse Sabre Turbo", model = "sabregt", class = "A" },
    { name = "Vapid Slamvan", model = "slamvan", class = "A" },
    { name = "Vapid Slamvan Custom", model = "slamvan3", class = "A" },
    { name = "Declasse Tampa", model = "tampa", class = "A" },
    { name = "Declasse Yosemite", model = "yosemite", class = "A" },
    { name = "Ubermacht Sentinel SG4", model = "sentinelsg4", class = "A" },
    { name = "Ocelot Locust", model = "locust", class = "A" },
    { name = "Ocelot Lynx", model = "lynx", class = "A" },
    { name = "Maibatsu Penumbra FF", model = "penumbra2", class = "A" },
    { name = "Obey 8F Drafter", model = "drafter", class = "A" },
    { name = "Toundra Panthere", model = "panthere", class = "A" },
    { name = "Annis 300R", model = "r300", class = "A" },
    { name = "Declasse Tahoma Coupe", model = "tahoma", class = "A" },
    { name = "Declasse Tulip M-100", model = "tulip2", class = "A" },
    -- CUSTOM- A Class:
    { name = "Dodge Challenger", model = "16challenger", class = "A" },
    { name = "2016 Dodge Charger", model = "16charger", class = "A" },
    { name = "2021 Chevrolet Camaro", model = "21camaro", class = "A" },
    { name = "1967 Ford Mustang GT500", model = "67GT500", class = "A" },
    { name = "1999 Dodge Viper", model = "99viper", class = "A" },
    { name = "Audi RS6", model = "rs6", class = "A" },
    { name = "BMW M2", model = "m2", class = "A" },
    { name = "BMW M3", model = "bmwm3e92", class = "A" },
    { name = "BMW M3 GTS", model = "m3e92gts", class = "A" },
    { name = "BMW M3 E36", model = "rmodm3e36", class = "A" },
    { name = "BMW M3 E46", model = "M3E46", class = "A" },
    { name = "BMW M4", model = "f82", class = "A" },
    { name = "BMW M4", model = "f82hs", class = "A" },
    { name = "BMW M4", model = "f82lw", class = "A" },
    { name = "BMW M4", model = "f82st", class = "A" },
    { name = "BMW M4", model = "f824slw", class = "A" },
    { name = "BMW M5", model = "bmci", class = "A" },
    { name = "BMW M5 E60", model = "m5e60", class = "A" },
    { name = "BMW M8", model = "bmwm8", class = "A" },
    { name = "Chevrolet Camaro", model = "zl12017", class = "A" },
    { name = "Chevrolet C7", model = "c7", class = "A" },
    { name = "Ford Mustang", model = "mgt", class = "A" },
    { name = "2016 Cadillac CTS-V", model = "ctsv16", class = "A" },
    { name = "2018 Honda Civic Type-R", model = "FK8", class = "A" },
    { name = "Jeep SRT8", model = "srt8", class = "A" },
    { name = "2020 Lexus LC500", model = "lc500", class = "A" },
    { name = "2017 Mercedes-Benz S63 AMG Cabriolet", model = "mers63c", class = "A" },
    { name = "Chevorlet Corvette C8", model = "stingray", class = "A" },
    { name = "Mercedes GT63", model = "rmodgt63", class = "A" },
    { name = "Mercedes C63 AMG", model = "C63AMG", class = "A" },
    { name = "2020 Audi RS6 Avant", model = "rs62", class = "A" },
    { name = "BMW 1100R Street Fighter", model = "BMW1100R", class = "A" },
    { name = "2016 BMW S1000RR", model = "BMWS1000RR", class = "A" },
    { name = "2017 Subaru WRX STI", model = "sti17", class = "A" },
    { name = "Toyota Supra Mk4", model = "supra2", class = "A" },
    { name = "2016 Maserati GranTurismo", model = "stradale18", class = "A" },
    { name = "Tesla Model S Prior Design", model = "teslapd", class = "E" }, -- ELECTRIC
    { name = "Tesla Model S", model = "models", class = "E" }, -- ELECTRIC
    { name = "Tesla Model S", model = "teslamodels", class = "E" }, -- ELECTRIC
    { name = "Tesla Model X", model = "teslax", class = "E" }, -- ELECTRIC
    { name = "Bentley Bacalar", model = "rmodbacalar", class = "A" },
    { name = "Aston Martin DBS", model = "rmodmartin", class = "A" },
    { name = "Ford Raptor Pandem", model = "razerpandemraptor", class = "A" },
    { name = "Chrysler 300 SRT8", model = "300srt8", class = "A" },
    { name = "Porsche Taycan", model = "taycan", class = "E" }, -- ELECTRIC
    { name = "Kawasaki H2R", model = "ninjah2", class = "A" },
    { name = "Kawasaki Z1000", model = "z1000", class = "A" },
    { name = "Ducati Panigale", model = "panigale", class = "A" },
    { name = "Yamaha R1", model = "yamahar1", class = "A" },
    { name = "Dodge Hellephant Durango", model = "hellephantdurango", class = "A"},
    { name = "1977 Ford Mustang Boss", model = "rr70bosswide", class = "A" },
    { name = "Lexus RC-F", model = "rrrcf", class = "A" },
    { name = "Karin Rebel Custom", model = "rebeld", class = "A" },
    { name = "Mitsubishi Lancer Evolution IX Voltex", model = "topfoil", class = "A" },
    { name = "2012 Mercedes-Benz C63 AMG Coupe Black Series", model = "mbc63", class = "A" },
    { name = "1969 Dodge Charger", model = "rmodcharger69", class = "A" },
    -- B Class:**
    { name = "Declasse Hotring Sabre", model = "hotring", class = "B" },
    { name = "Imponte Beater Dukes", model = "dukes3", class = "B" },
    { name = "Pegassi Monroe", model = "monroe", class = "B" },
    { name = "Dinka RT3000", model = "rt3000", class = "B" },
    { name = "Dinka Kanjo", model = "kanjo", class = "B" },
    { name = "Karin Previon", model = "previon", class = "B" },
    { name = "Karin Calico GTF", model = "calico", class = "B" },
    { name = "Annis ZR350", model = "zr350", class = "B" },
    { name = "Annis Euros", model = "euros", class = "B" },
    { name = "Lampadati Komoda", model = "komoda", class = "B" },
    { name = "Dinka Blista", model = "blista", class = "B" },
    { name = "Dinka Sugoi", model = "sugoi", class = "B" },
    { name = "Bollokon Prairie", model = "prairie", class = "B" },
    { name = "Annis Savestra", model = "savestra", class = "B" },
    { name = "Ubermacht Sentinel", model = "sentinel", class = "B" },
    { name = "Ubermacht Sentinel XS", model = "sentinel2", class = "B" },
    { name = "Ubermacht Zion Classic", model = "zion3", class = "B" },
    { name = "Bravado Buffalo", model = "buffalo", class = "B" },
    { name = "Bravado Buffalo S", model = "buffalo2", class = "B" },
    { name = "Bravado Buffalo STX", model = "buffalo4_USA", class = "B" },
    { name = "Enus Windsor Drop", model = "windsor2", class = "B" },
    { name = "Enus Jubilee", model = "jubilee_USA", class = "B" },
    { name = "Enus Deity", model = "deity_USA", class = "B" },
    { name = "Shyster Fusilade", model = "fusilade", class = "B" },
    { name = "Karin Futo", model = "futo", class = "B" },
    { name = "Karin Kuruma", model = "kuruma", class = "B" },
    { name = "Karin Sultan MKIII", model = "sultan", class = "B" },
    { name = "Karin Sultan MKII", model = "sultan2", class = "B" },
    { name = "Karin Sultan RS Classic", model = "sultan3", class = "B" },
    { name = "Ubermacht Revolter", model = "revolter", class = "B" },
    { name = "Ubermacht Schafter", model = "schafter2", class = "B" },
    { name = "Ubermacht Schafter V12", model = "schafter3", class = "B" },
    { name = "Ubermacht Schafter V12 LWB", model = "schafter4", class = "B" },
    { name = "Ubermacht Sentinel Classic", model = "sentinel3", class = "B" },
    { name = "Enus Cognoscenti", model = "cognoscenti", class = "B" },
    { name = "Enus Cognoscenti 55", model = "cog55", class = "B" },
    { name = "Cheval Fugitive", model = "fugitive", class = "B" },
    { name = "Karin Intruder", model = "intruder", class = "B" },
    { name = "Declasse Premier", model = "premier", class = "B" },
    { name = "Zirconium Stratum", model = "stratum", class = "B" },
    { name = "Enus Super Diamond", model = "superd", class = "B" },
    { name = "Obey Tailgater", model = "tailgater", class = "B" },
    { name = "Dewbauchee Exemplar", model = "exemplar", class = "B" },
    { name = "Ocelot Jackal", model = "jackal", class = "B" },
    { name = "Ubermacht Oracle", model = "oracle", class = "B" },
    { name = "Ubermacht Oracle XS", model = "oracle2", class = "B" },
    { name = "Lampadati Felon", model = "felon", class = "B" },
    { name = "Lampadati Cinquemila", model = "cinquemila_USA", class = "B" },
    { name = "Pfister Astron", model = "astron_USA", class = "B" },
    { name = "Obey I-Wagen", model = "iwagen_USA", class = "E" }, -- ELECTRIC
    { name = "Coil Raiden", model = "raiden", class = "E" }, -- ELECTRIC
    { name = "Pfister Neon", model = "neon", class = "E" }, -- ELECTRIC
    { name = "Coil Cyclone", model = "cyclone", class = "E" }, -- ELECTRIC
    { name = "Cheval Surge", model = "surge", class = "E" }, -- ELECTRIC
    { name = "Ubermacht Rebla", model = "rebla", class = "B" },
    { name = "Gallivanter Baller LE", model = "baller3", class = "B" },
    { name = "Gallivanter Baller ST", model = "baller7_USA", class = "B" },
    { name = "Benefactor Dubsta Mandem", model = "dubsta2", class = "B" },
    { name = "Benefactor Dubsta", model = "dubsta", class = "B" },
    { name = "Bravado Gresley", model = "gresley", class = "B" },
    { name = "Enus Huntley S", model = "huntley", class = "B" },
    { name = "Obey Rocoto", model = "rocoto", class = "B" },
    { name = "Benefactor Serrano", model = "serrano", class = "B" },
    { name = "Benefactor XLS", model = "xls", class = "B" },
    { name = "Vapid Scuffvan Custom", model = "minivan2", class = "B" },
    { name = "Obey Omnis e-GT", model = "omnisegt", class = "B" },
    { name = "Rhinehart", model = "rhinehart", class = "B" },
    { name = "Imponte Ruiner ZZ-8", model = "ruiner4", class = "B" },
    { name = "Ubermacht Sentinel Classic Widebody", model = "sentinel4", class = "B" },
    { name = "Declasse Draugur", model = "draugur", class = "B" },
    { name = "BF Weevil Custom", model = "weevil2", class = "B" },
    { name = "Weeny Issi Sport", model = "issi7", class = "B" },
    { name = "Vapid Flash GT", model = "flashgt", class = "B" },
    { name = "Obey Omnis", model = "omnis", class = "B" },
    { name = "Lampadati Tropos Rallye", model = "tropos", class = "B" },
    { name = "Vapid GB200", model = "gb200", class = "B" },
    { name = "Lampadati Michelli GT", model = "michelli", class = "B" },
    { name = "Nagasaki Outlaw", model = "outlaw", class = "B" },
    { name = "Karin Everon", model = "everon", class = "B" },
    { name = "Annis Hellion", model = "hellion", class = "B" },
    { name = "Vapid Trophy Truck", model = "trophytruck", class = "B" },
    { name = "Vapid Desert Raid", model = "trophytruck2", class = "B" },
    { name = "Vapid Slamvan", model = "slamvan2", class = "B" },
    { name = "RUNE Cheburek", model = "cheburek", class = "B" },
    { name = "Albany Buccaneer", model = "buccaneer", class = "B" },
    { name = "Albany Buccaneer Custom", model = "buccaneer2", class = "B" },
    { name = "Vapid Clique", model = "clique", class = "B" },
    { name = "Willard Faction", model = "faction", class = "B" },
    { name = "Willard Faction Custom", model = "faction2", class = "B" },
    { name = "Declasse Impaler", model = "impaler", class = "B" },
    { name = "Imponte Nightshade", model = "nightshade", class = "B" },
    { name = "Imponte Phoenix", model = "phoenix", class = "B" },
    { name = "Cheval Picador", model = "picador", class = "B" },
    { name = "Bravado Rat-Truck", model = "ratloader2", class = "B" },
    { name = "Declasse Sabre Turbo Custom", model = "sabregt2", class = "B" },
    { name = "Declasse Stallion", model = "stalion", class = "B" },
    { name = "Declasse Tulip", model = "tulip", class = "B" },
    { name = "Declasse Vigero", model = "vigero", class = "B" },
    { name = "Albany Virgo", model = "virgo", class = "B" },
    { name = "Benefactor Stirling GT", model = "feltzer3", class = "B" },
    { name = "Lampadati Casco", model = "casco", class = "B" },
    { name = "Invetero Coquette Classic", model = "coquette2", class = "B" },
    { name = "Invetero Coquette Blackfin", model = "coquette3", class = "B" },
    { name = "Grotti GT500", model = "gt500", class = "B" },
    { name = "Declasse Mamba", model = "mamba", class = "B" },
    { name = "Grotti Stinger", model = "stinger", class = "B" },
    { name = "Grotti Stinger GT", model = "stingergt", class = "B" },
    { name = "Ocelot Swinger", model = "swinger", class = "B" },
    { name = "Lampadati Viseris", model = "viseris", class = "B" },
    { name = "Dewbauchee Rapid GT Classic", model = "rapidgt3", class = "B" },
    { name = "Bravado Gauntlet Classic", model = "gauntlet3", class = "B" },
    { name = "Bravado Gauntlet Classic Custom", model = "gauntlet5", class = "B" },
    { name = "Coil Savanna", model = "savanna", class = "B" },
    { name = "Albany VSTR", model = "vstr", class = "B" },
    { name = "Lampadati Novak", model = "novak", class = "B" },
    { name = "BF Club", model = "club", class = "B" },
    { name = "Vapid Retinue", model = "retinue", class = "B" },
    { name = "Vapid Retinue MkII", model = "retinue2", class = "B" },
    { name = "Maxwell Vagrant", model = "vagrant", class = "B" },
    { name = "Weeny Issi Sport", model = "issi8", class = "B" },
    -- CUSTOM- B Class:
    { name = "Toyota 4Runner", model = "4runner", class = "B" },
    { name = "2019 Mercedes-Benz S650 Maybach", model = "19S650", class = "B" },
    { name = "2021 Cadillac Escalade", model = "21escalade", class = "B" },
    { name = "1993 Porsche 928 GTS", model = "928gts", class = "B" },
    { name = "1979 Chevrolet Hoonigan K5 Blazer", model = "k5", class = "B" },
    { name = "2002 Chevrolet Camaro", model = "camaro02", class = "B" },
    { name = "2008 Chevrolet Tahoe", model = "tahoe08", class = "B" },
    { name = "2021 Ford Bronco Wildtrak", model = "wildtrak", class = "B" },
    { name = "2016 Bentley Bentayga", model = "bbentayga", class = "B" },
    { name = "Mercedes-Benz E55 AMG", model = "benze55", class = "B" },
    { name = "BMW E30", model = "alpinae30", class = "B" },
    { name = "BMW E34", model = "e34", class = "B" },
    { name = "2016 BMW X5", model = "x5m2016", class = "B" },
    { name = "2020 BMW i4", model = "ocni422spe", class = "E" }, -- ELECTRIC
    { name = "BMW Z3", model = "z3", class = "B" },
    { name = "Subaru BRZ", model = "brz13", class = "B" },
    { name = "Chevrolet C-10 Stepside Custom", model = "c10custom", class = "B" },
    { name = "1969 Chevrolet Camaro SS", model = "camaro69", class = "B" },
    { name = "1970 Chevrolet Camaro Z28", model = "camaro70", class = "B" },
    { name = "2018 Can Am Maverick", model = "can", class = "B" },
    { name = "2020 Lincoln Continental (Custom Wheels)", model = "cont", class = "B" },
    { name = "1970 Chevrolet Corvette", model = "corvette70", class = "B" },
    { name = "Ford Crown Victoria", model = "crownvic2011", class = "B" },
    { name = "Rolls Royce Cullinan", model = "cullinan", class = "B" },
    { name = "2001 Honda Civic Type-R ", model = "ep3", class = "B" },
    { name = "Ford F350", model = "wdf350", class = "B" },
    { name = "2021 Ford F-450 Platinum", model = "f450plat", class = "B" },
    { name = "1999 Ford F-150 SVT Lightning", model = "flightning99", class = "B" },
    { name = "1932 Ford HulaGirl", model = "ford32hulagirl", class = "B" },
    { name = "1932 Ford V-8 Coupé 2", model = "fordc32h", class = "B" },
    { name = "Ford F150 Raptor", model = "f150", class = "B" },
    { name = "Ford F150 Raptor 2", model = "foxraptor", class = "B" },
    { name = "Mercedes-Benz G-Class Brabus", model = "w463a1", class = "B" },
    { name = "Volkswagon Golf GTI", model = "golfgti", class = "B" },
    { name = "Jeep Gladiator", model = "jeepg", class = "B" },
    { name = "2020 Land Rover Range Rover Vogue Mansory", model = "mansrr", class = "B" },
    { name = "Maserati Levante Novitec", model = "mlnovitec", class = "B" },
    { name = "2020 Chrysler Pacifica Limited S", model = "pacificasb", class = "B" },
    { name = "2016 Volkswagen Passat", model = "passat", class = "B" },
    { name = "Peugeot 206 GTi", model = "peugeot206", class = "B" },
    { name = "2006 GMC Sierra", model = "polar06seirra", class = "B" },
    { name = "Dodge Ram SRT-10", model = "ramsrt10", class = "B" },
    { name = "Toyota Supra", model = "rmodsuprapandem", class = "B" },
    { name = "Mazda RX-7", model = "rx7rb", class = "B" },
    { name = "Chevrolet Silverado 2500 HD", model = "silv2500hd", class = "B" },
    { name = "Chevrolet Silverado (Single Cab)", model = "silv20", class = "B" },
    { name = "Subaru WRX STI", model = "subisti08", class = "B" },
    { name = "2004 Subaru WRX STI", model = "subwrx", class = "B" },
    { name = "2016 Rolls Royce Wraith", model = "wraith", class = "B" },
    { name = "2018 GMC CadimaX 3500HD", model = "GODzBGDCADIMAX", class = "B" },
    { name = "2020 Ford F-450", model = "20f450", class = "B" },
    { name = "2020 Ford F-350", model = "f350d", class = "B" },
    { name = "2020 GMC Sierra 3500HD", model = "GODz3500HDWELDER", class = "B" },
    { name = "Volkswagon Golf (Mk6)", model = "golfmk6", class = "B" },
    { name = "Acura RSX (DC5)", model = "dc5", class = "B" },
    { name = "Audi A6", model = "a6", class = "B" },
    { name = "Voodoo Caddy S", model = "voodoo_caddys", class = "B" },
    { name = "Nissan 370z", model = "370z", class = "B" },
    { name = "2019 Dodge Ram Donk", model = "19ramdonk", class = "B" },
    { name = "GMC Denali", model = "denali18", class = "B" },
    { name = "Dodge Ram TRX", model = "dodgetrx", class = "B" },
    { name = "Ford F100 Slammed", model = "slammedf100", class = "B" },
    { name = "2009 Ford Focus RS", model = "09fordRS", class = "B" },
    { name = "2017 Ford Focus RS", model = "17fordRS", class = "B" },
    { name = "Dababy Car", model = "dababy", class = "B" },
    { name = "Ford Mach E", model = "mache", class = "E" }, -- ELECTRIC
    { name = "Audi e-tron GT", model = "ocnetrongt", class = "E" }, -- ELECTRIC
    { name = "2018 Harley Davidson FLHXS", model = "flhxs_streetglide_special18", class = "B" },
    { name = "Harley Davidson Road King", model = "na25", class = "B" },
    { name = "2022 Sur Ron Lightbee Pxx", model = "22Surron", class = "B" },
    { name = "Ford F100 Trophy", model = "f100trophy", class = "B" },
    { name = "Progen Proff", model = "proff", class = "B" },
    { name = "Dodge Ram 1500 Custom", model = "gcram1500", class = "B" },
    { name = "Spyker C8", model = "spyker", class = "B" },
    { name = "Pontiac G8", model = "pontiacg8", class = "B" },
    { name = "Xpeng P7", model = "x3p720", class = "E" }, -- ELECTRIC
    { name = "Dodge 2500", model = "bcbruiser", class = "B" },
    { name = "Dodge 3500", model = "bcys", class = "B" },
    { name = "Dodge 3500 HD", model = "bc203500hd", class = "B"},
    { name = "Chevrolet C10", model = "bcc10c", class = "B"},
    { name = "Karin Ariant", model = "ariant", class = "B"},
    { name = "Karin Asteropers", model = "asteropers", class = "B"},
    { name = "Mercedes-Benz 190E Evolution II", model = "190e", class = "B"},
    { name = "2006 Pontiac GTO", model = "gto06", class = "B"},
    { name = "1969 Pontiac GTO The Judge", model = "judge", class = "B"},
    { name = "1987 Mercedes Benz AMG Hammer Coupe", model = "amgh", class = "B"},
    { name = "1969 Pontiac Firebird Trans AM", model = "trans69", class = "B"},
    { name = "2016 Mazda MX5 Pandem", model = "mxpan", class = "B"},
    -- C Class:**
    { name = "Declasse Yosemite Rancher", model = "yosemite3", class = "C" },
    { name = "Dinka Blista Compact", model = "blista2", class = "C" },
    { name = "Karin Asterope", model = "asterope", class = "C" },
    { name = "Vulcar Ingot", model = "ingot", class = "C" },
    { name = "Albany Primo", model = "primo", class = "C" },
    { name = "Albany Primo Custom", model = "primo2", class = "C" },
    { name = "Vapid Stanier", model = "stanier", class = "C" },
    { name = "Vapid Taxi", model = "taxi", class = "C" },
    { name = "Dundreary Stretch", model = "stretch", class = "C" },
    { name = "Vulcar Warrener", model = "warrener", class = "C" },
    { name = "Albany Washington", model = "washington", class = "C" },
    { name = "Weeny Issi", model = "issi2", class = "C" },
    { name = "Benefactor Panto", model = "panto", class = "C" },
    { name = "Declasse Rhapsody", model = "rhapsody", class = "C" },
    { name = "Annis Remus", model = "remus", class = "C" },
    { name = "Gallivanter Baller", model = "baller", class = "C" },
    { name = "Gallivanter Baller", model = "baller2", class = "C" },
    { name = "Karin BeeJay XL", model = "bjxl", class = "C" },
    { name = "Albany Cavalcade", model = "cavalcade", class = "C" },
    { name = "Albany Cavalcade", model = "cavalcade2", class = "C" },
    { name = "Fathom FQ-2", model = "fq2", class = "C" },
    { name = "Declasse Granger", model = "granger", class = "C" },
    { name = "Declasse Granger 3600LX", model = "granger2_USA", class = "C" },
    { name = "Emperor Habanero", model = "habanero", class = "C" },
    { name = "Dundreary Landstalker", model = "landstalker", class = "C" },
    { name = "Mammoth Patriot", model = "patriot", class = "C" },
    { name = "Mammoth Patriot WCR", model = "patriot2", class = "C" },
    { name = "Mammoth Patriot Mil-Spec", model = "patriot3_USA", class = "C" },
    { name = "Vapid Radius", model = "radi", class = "C" },
    { name = "Canis Seminole", model = "seminole", class = "C" },
    { name = "Canis Seminole Frontier", model = "seminole2", class = "C" },
    { name = "Bravado Youga", model = "youga", class = "C" },
    { name = "Grotti Brioso 300 Widebody", model = "brioso3", class = "C" },
    { name = "Dinka Kanjo SJ", model = "kanjosj", class = "C" },
    { name = "Dinka Postlude", model = "postlude", class = "C" },
    { name = "Bravado Greenwood", model = "greenwood", class = "C" },
    { name = "MTL Dune", model = "rallytruck", class = "C" },
    { name = "Vapid Caracara", model = "caracara2", class = "C" },
    { name = "Vapid Contender", model = "contender", class = "C" },
    { name = "Bravado Rumpo Custom", model = "rumpo3", class = "C" },
    { name = "Benefactor Streiter", model = "streiter", class = "C" },
    { name = "Canis Mesa", model = "mesa", class = "C" },
    { name = "Canis Mesa Lifted", model = "mesa3", class = "C" },
    { name = "Pfister Comet Safari", model = "comet4", class = "C" },
    { name = "BF Bifta", model = "bifta", class = "C" },
    { name = "Nagasaki Street Blazer", model = "blazer4", class = "C" },
    { name = "Coil Brawler", model = "brawler", class = "C" },
    { name = "Benefactor Dubsta 6x6", model = "dubsta3", class = "C" },
    { name = "BF Dune Buggy", model = "dune", class = "C" },
    { name = "BF Injection", model = "bfinjection", class = "C" },
    { name = "Canis Kamacho", model = "kamacho", class = "C" },
    { name = "Karin Rebel", model = "rebel", class = "C" },
    { name = "Karin Rebel", model = "rebel2", class = "C" },
    { name = "Vapid Guardian", model = "guardian", class = "C" },
    { name = "Bravado Bison", model = "bison", class = "C" },
    { name = "Vapid Bobcat XL", model = "bobcatxl", class = "C" },
    { name = "Vapid Riata", model = "riata", class = "C" },
    { name = "Benefactor Glendale", model = "glendale", class = "C" },
    { name = "Vulcar Fagaloa", model = "fagaloa", class = "C" },
    { name = "Weeny Issi Classic", model = "issi3", class = "C" },
    { name = "Willard Faction Donk", model = "faction3", class = "C" },
    { name = "Vapid Chino", model = "chino", class = "C" },
    { name = "Vapid Chino Custom", model = "chino2", class = "C" },
    { name = "Vapid Hotknife", model = "hotknife", class = "C" },
    { name = "Albany Roosevelt", model = "btype", class = "C" },
    { name = "Albany Roosevelt Valor", model = "btype3", class = "C" },
    { name = "Truffade Z-Type", model = "ztype", class = "C" },
    { name = "Declasse Moonbeam", model = "moonbeam", class = "C" },
    { name = "Declasse Moonbeam Custom", model = "moonbeam2", class = "C" },
    { name = "Bravado Rat-Loader", model = "ratloader", class = "C" },
    { name = "Dewbauchee JB 700", model = "jb7002", class = "C" },
    { name = "Vulcar Nebula Turbo", model = "nebula", class = "C" },
    { name = "Imponte Deluxo", model = "deluxo2", class = "C" },
    { name = "Benefactor Glendale Custom", model = "glendale2", class = "C" },
    { name = "Dundreary Landstalker XL", model = "landstlkr2", class = "C" },
    { name = "Coil Brawler HOA", model = "hoabrawler", class = "C" },
    { name = "Canis Freecrawler", model = "freecrawler", class = "C" },
    { name = "Karin Boor", model = "boor", class = "C" },
    { name = "Classique Broadway", model = "broadway", class = "C" },
    { name = "Bravado", model = "eudora", class = "C" },
    -- CUSTOM- C Class:
    { name = "1996 Chevrolet Impala SS", model = "impala", class = "C" },
    { name = "1959 Chevrolet Impala", model = "impala59c", class = "C" },
    { name = "Porsche 356", model = "356ac", class = "C" },
    { name = "1978 Ford F150", model = "f15078", class = "C" },
    { name = "1973 Chevrolet Caprice Nip Donk", model = "brainshack", class = "C" },
    { name = "1957 Ferrari California", model = "cali57", class = "C" },
    { name = "Chevrolet Caprice (Donk)", model = "trixbox", class = "C" },
    { name = "Chevrolet Nova", model = "nova66", class = "C" },
    { name = "Ford Galaxie", model = "galaxie", class = "C" },
    { name = "Mercedes-Benz 300 SL", model = "mb300sl", class = "C" },
    { name = "Volkswagon Golf (MK3)", model = "mk3", class = "C" },
    { name = "1973 Porsche 911", model = "porrs73", class = "C" },
    { name = "1986 Chevrolet Silverado", model = "SILV86", class = "C" },
    { name = "Weeny Tamworth", model = "tamworth", class = "C" },
    { name = "1962 Volkswagon Type 2", model = "type262", class = "C" },
    { name = "1963 Volkswagon Type 2", model = "type263", class = "C" },
    { name = "1966 Volkswagon Type 2", model = "type266", class = "C" },
    { name = "2000 Ford F350 Dually", model = "00f350d", class = "C" },
    { name = "Hummer H2", model = "H2", class = "C" },
    -- D Class:**
    { name = "Bravado Youga Classic 4x4", model = "youga3", class = "D" },
    { name = "Bravado Youga Custom", model = "youga4_USA", class = "D" },
    { name = "Albany Manana Custom", model = "manana2", class = "D" },
    { name = "Declasse Asea", model = "asea", class = "D" },
    { name = "Declasse Silverstar", model = "silverstar", class = "D" },
    { name = "Declasse Silverstar 2", model = "silverstar2", class = "D" },
    { name = "Declasse Emperor", model = "emperor", class = "D" },
    { name = "Declasse Emperor", model = "emeperor2", class = "D" },
    { name = "Dundreary Regina", model = "regina", class = "D" },
    { name = "Vapid Minivan", model = "minivan", class = "D" },
    { name = "Bravado Paradise", model = "paradise", class = "D" },
    { name = "Brute Pony", model = "pony", class = "D" },
    { name = "Bravado Rumpo News", model = "rumpo", class = "D" },
    { name = "Bravado Rumpo HerrKutz", model = "rumpo2", class = "D" },
    { name = "Vapid Speedo", model = "speedo", class = "D" },
    { name = "Brute Camper", model = "camper", class = "D" },
    { name = "Declasse Burrito", model = "burrito3", class = "D" },
    { name = "Canis Kalahari", model = "kalahari", class = "D" },
    { name = "Karin Dilettante", model = "dilettante", class = "E" }, -- ELECTRIC
    { name = "Karin Dilettante Patrol", model = "dilettante2", class = "E" }, -- ELECTRIC
    { name = "Nagasaki Blazer", model = "blazer", class = "D" },
    { name = "Nagasaki Lifeguard", model = "blazer2", class = "D" },
    { name = "Canis Bodhi", model = "bodhi2", class = "D" },
    { name = "Declasse Rancher XL", model = "rancherxl", class = "D" },
    { name = "Bravado Duneloader", model = "dloader", class = "D" },
    { name = "Vapid Sadler", model = "sadler", class = "D" },
    { name = "Vapid Sandking", model = "sandking2", class = "D" },
    { name = "Vapid Sandking XL", model = "sandking", class = "D" },
    { name = "BF Surfer", model = "surfer", class = "D" },
    { name = "BF Surfer Kona", model = "surfer2", class = "D" },
    { name = "BF Surfer Custom", model = "surfer3", class = "D" },
    { name = "Albany Hermes", model = "hermes", class = "D" },
    { name = "Albany Virgo Custom", model = "virgo2", class = "D" },
    { name = "Albany Virgo Classic", model = "virgo3", class = "D" },
    { name = "Declasse Voodoo", model = "voodoo2", class = "D" },
    { name = "Declasse Voodoo Custom", model = "voodoo", class = "D" },
    { name = "Albany Manana", model = "manana", class = "D" },
    { name = "Vapid Peyote", model = "peyote", class = "D" },
    { name = "Declasse Tornado", model = "tornado", class = "D" },
    { name = "Declasse Tornado Cabrio", model = "tornado2", class = "D" },
    { name = "Declasse Tornado", model = "tornado3", class = "D" },
    { name = "Declasse Tornado Custom", model = "tornado5", class = "D" },
    { name = "Lampadati Pigalle", model = "pigalle", class = "D" },
    { name = "Zirconium Journey", model = "journey", class = "D" },
    { name = "Zirconium Journey II", model = "journey2", class = "D" },
    { name = "Bravado Youga Classic", model = "youga2", class = "D" },
    { name = "BF Weevil", model = "weevil", class = "D" },
    { name = "Chillybin", model = "chillybin", class = "D" },
    { name = "Chariot Romero Hearse", model = "romero", class = "D" },
    { name = "Weeny Dynasty", model = "dynasty", class = "D" },
    { name = "Vapid Hustler", model = "hustler", class = "D" },
    -- CUSTOM- D Class:
    { name = "1932 Ford V-8 Coupé", model = "fordc32", class = "D" },
    { name = "1980 Ford Bronco", model = "80bronco", class = "D" },
}

RegisterServerCallback {
	eventName = 'rahe-racing:hasItem',
	eventCallback = function(source)
		local char = exports["usa-characters"]:GetCharacter(source)
        local reqItem = char.getItem("Tablet")
        if reqItem then
            return true
        end
        return false
	end
}
