RegisterServerEvent("parachute:usedParachute")
AddEventHandler("parachute:usedParachute", function()
	local char = exports["usa-characters"]:GetCharacter(source)
	char.removeItem("Parachute", 1)
end)
